import javax.swing.*;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.Enumeration;
import java.util.Objects;
import java.util.regex.Pattern;

/**
 *
 * @author narwa
 */
public class App extends javax.swing.JFrame {

    private final CardLayout formCards;
    private final HomePage homePage;
    
    /**
     * Default constructor tanpa home page (landing page).
     */
    public App() {
        /* Untuk tes: (tidak memiliki referensi HomePage) */
        this.homePage = null;
        initComponents();                                       // mengatur komponen JFrame
        setTitle("Sistem Manajemen Perpustakaan");              // mengatur judul jendela JFrame
        /* Mengatur icon/gambar judul pada window frame */
        setIconImage(
          new ImageIcon(
            Objects.requireNonNull(
              getClass().getResource("/images/bookIcon.png"))
          ).getImage()
        );
        /* Menyimpan format CardLayout untuk berpindah card panel */
        formCards = (CardLayout) formContainer.getLayout();
    }
    
    /**
     * Constructor dengan home page (landing page).
     */
    public App(HomePage homePage) {
        /* Referensi HomePage untuk melakukan log out */
        this.homePage = homePage;
        initComponents();                                       // mengatur komponen JFrame
        setTitle("Sistem Manajemen Perpustakaan");              // mengatur judul jendela JFrame
        /* Mengatur icon/gambar judul pada window frame */
        setIconImage(
          new ImageIcon(
            Objects.requireNonNull(
              getClass().getResource("/images/bookIcon.png"))
          ).getImage()
        );
        /* Menyimpan format CardLayout untuk berpindah card panel */
        formCards = (CardLayout) formContainer.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inp_regTipeKoleksi = new javax.swing.ButtonGroup();
        menuContainer = new javax.swing.JPanel();
        menuTitle = new javax.swing.JLabel();
        b_regPeminjam = new javax.swing.JButton();
        b_regKoleksi = new javax.swing.JButton();
        l_logoSadhar = new javax.swing.JLabel();
        formContainer = new javax.swing.JPanel();
        registrasiPeminjam = new javax.swing.JPanel();
        regisPeminjamTitle = new javax.swing.JLabel();
        l_nama = new javax.swing.JLabel();
        i_nama = new java.awt.TextField();
        l_noId = new javax.swing.JLabel();
        i_noId = new java.awt.TextField();
        i_jenisNoId = new javax.swing.JComboBox<>();
        l_alamat = new javax.swing.JLabel();
        i_alamat = new java.awt.TextField();
        l_telp = new javax.swing.JLabel();
        i_telp = new java.awt.TextField();
        l_maksPinjam = new javax.swing.JLabel();
        i_maksPinjam = new javax.swing.JSpinner();
        b_simpanRegPeminjam = new javax.swing.JButton();
        b_kosongkanRegPeminjam = new javax.swing.JButton();
        l_simpanPeminjamEmptyIndicator = new javax.swing.JLabel();
        registrasiKoleksi = new javax.swing.JPanel();
        registKoleksiTitle = new javax.swing.JLabel();
        l_judulKoleksi = new javax.swing.JLabel();
        i_judulKoleksi = new java.awt.TextField();
        l_penerbit = new javax.swing.JLabel();
        i_penerbit = new java.awt.TextField();
        l_judulBuku4 = new javax.swing.JLabel();
        i_jenisBuku = new javax.swing.JRadioButton();
        i_jenisMajalah = new javax.swing.JRadioButton();
        i_jenisDisk = new javax.swing.JRadioButton();
        l_isbnIssn = new javax.swing.JLabel();
        i_isbnIssn = new java.awt.TextField();
        l_jmlHalaman = new javax.swing.JLabel();
        i_jmlHalaman = new javax.swing.JSpinner();
        l_volume = new javax.swing.JLabel();
        i_volume = new javax.swing.JSpinner();
        l_seri = new javax.swing.JLabel();
        i_seri = new javax.swing.JSpinner();
        l_format = new javax.swing.JLabel();
        i_format = new javax.swing.JComboBox<>();
        b_simpanRegKoleksi = new javax.swing.JButton();
        b_kosongkanRegKoleksi = new javax.swing.JButton();
        l_simpanKoleksiEmptyIndicator = new javax.swing.JLabel();
        menuBarMain = new javax.swing.JMenuBar();
        menuBar_tambah = new javax.swing.JMenu();
        tambahPeminjam = new javax.swing.JMenuItem();
        tambahKoleksi = new javax.swing.JMenuItem();
        menuBar_edit = new javax.swing.JMenu();
        editPeminjam = new javax.swing.JMenuItem();
        editKoleksi = new javax.swing.JMenuItem();
        menuBar_transaksi = new javax.swing.JMenu();
        transaksiPinjam = new javax.swing.JMenuItem();
        transaksiKembali = new javax.swing.JMenuItem();
        menuBar_koleksi = new javax.swing.JMenu();
        koleksiBuku = new javax.swing.JMenuItem();
        koleksiMajalah = new javax.swing.JMenuItem();
        koleksiDisk = new javax.swing.JMenuItem();
        menuBar_informasi = new javax.swing.JMenu();
        menuBar_keluar = new javax.swing.JMenu();
        logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Manajemen Data Perpustakaan");
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1280, 720));
        setMinimumSize(new java.awt.Dimension(960, 540));
        setResizable(false);

        menuContainer.setBackground(new java.awt.Color(153, 204, 255));

        menuTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuTitle.setForeground(new java.awt.Color(51, 102, 255));
        menuTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTitle.setText("<html>Sistem Manajemen<br/>Perpustakaan</html>");

        b_regPeminjam.setBackground(new java.awt.Color(153, 153, 255));
        b_regPeminjam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_regPeminjam.setForeground(new java.awt.Color(255, 255, 255));
        b_regPeminjam.setText("Registrasi Peminjam");
        b_regPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_regPeminjamActionPerformed(evt);
            }
        });

        b_regKoleksi.setBackground(new java.awt.Color(153, 153, 255));
        b_regKoleksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_regKoleksi.setForeground(new java.awt.Color(255, 255, 255));
        b_regKoleksi.setText("Registrasi Koleksi");
        b_regKoleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_regKoleksiActionPerformed(evt);
            }
        });

        l_logoSadhar.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoSanataDharma.png")).getImage().getScaledInstance(180, 180, Image.SCALE_SMOOTH)));

        javax.swing.GroupLayout menuContainerLayout = new javax.swing.GroupLayout(menuContainer);
        menuContainer.setLayout(menuContainerLayout);
        menuContainerLayout.setHorizontalGroup(
            menuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuTitle)
                    .addComponent(b_regPeminjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_regKoleksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_logoSadhar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        menuContainerLayout.setVerticalGroup(
            menuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_regPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_regKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_logoSadhar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        formContainer.setBackground(new java.awt.Color(255, 255, 255));
        formContainer.setLayout(new java.awt.CardLayout());

        registrasiPeminjam.setPreferredSize(new java.awt.Dimension(700, 540));

        regisPeminjamTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        regisPeminjamTitle.setText("Registrasi Data Peminjam");

        l_nama.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_nama.setText("Nama Lengkap");
        l_nama.setMaximumSize(new java.awt.Dimension(150, 25));
        l_nama.setMinimumSize(new java.awt.Dimension(150, 25));

        i_nama.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        i_nama.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_nama.setName(""); // NOI18N
        i_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_namaActionPerformed(evt);
            }
        });

        l_noId.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_noId.setText("Nomor Identitas");
        l_noId.setMaximumSize(new java.awt.Dimension(150, 25));
        l_noId.setMinimumSize(new java.awt.Dimension(150, 25));

        i_noId.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_noId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                i_noIdFocusLost(evt);
            }
        });
        i_noId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_noIdActionPerformed(evt);
            }
        });

        i_jenisNoId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        i_jenisNoId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIM", "NIP", "NIK" }));
        i_jenisNoId.setToolTipText("Jenis Nomor Identitas");
        i_jenisNoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_jenisNoIdActionPerformed(evt);
            }
        });

        l_alamat.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_alamat.setText("Alamat");
        l_alamat.setMaximumSize(new java.awt.Dimension(150, 25));
        l_alamat.setMinimumSize(new java.awt.Dimension(150, 25));

        i_alamat.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_alamatActionPerformed(evt);
            }
        });

        l_telp.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_telp.setText("Nomor Telepon");
        l_telp.setMaximumSize(new java.awt.Dimension(150, 25));
        l_telp.setMinimumSize(new java.awt.Dimension(150, 25));

        i_telp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_telp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                i_telpFocusLost(evt);
            }
        });
        i_telp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_telpActionPerformed(evt);
            }
        });

        l_maksPinjam.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_maksPinjam.setText("Maks. Pinjaman");
        l_maksPinjam.setMaximumSize(new java.awt.Dimension(150, 25));
        l_maksPinjam.setMinimumSize(new java.awt.Dimension(150, 25));

        i_maksPinjam.setModel(new javax.swing.SpinnerNumberModel(1, 0, 10, 1));

        b_simpanRegPeminjam.setBackground(new java.awt.Color(51, 204, 0));
        b_simpanRegPeminjam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_simpanRegPeminjam.setForeground(new java.awt.Color(255, 255, 255));
        b_simpanRegPeminjam.setText("Simpan");
        b_simpanRegPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_simpanRegPeminjamActionPerformed(evt);
            }
        });

        b_kosongkanRegPeminjam.setBackground(new java.awt.Color(255, 102, 102));
        b_kosongkanRegPeminjam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_kosongkanRegPeminjam.setForeground(new java.awt.Color(255, 255, 255));
        b_kosongkanRegPeminjam.setText("Kosongkan");
        b_kosongkanRegPeminjam.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b_kosongkanRegPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_kosongkanRegPeminjamActionPerformed(evt);
            }
        });

        l_simpanPeminjamEmptyIndicator.setBackground(new java.awt.Color(153, 153, 153));
        l_simpanPeminjamEmptyIndicator.setForeground(new java.awt.Color(255, 51, 51));
        l_simpanPeminjamEmptyIndicator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_simpanPeminjamEmptyIndicator.setText("Terdapat data yang masih kosong atau tidak benar!");
        l_simpanPeminjamEmptyIndicator.setVisible(false);

        javax.swing.GroupLayout registrasiPeminjamLayout = new javax.swing.GroupLayout(registrasiPeminjam);
        registrasiPeminjam.setLayout(registrasiPeminjamLayout);
        registrasiPeminjamLayout.setHorizontalGroup(
            registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrasiPeminjamLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrasiPeminjamLayout.createSequentialGroup()
                        .addGroup(registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regisPeminjamTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(registrasiPeminjamLayout.createSequentialGroup()
                                .addGroup(registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(l_telp, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(l_noId, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(l_alamat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(l_maksPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(l_nama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                .addGap(15, 15, 15)
                                .addGroup(registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(registrasiPeminjamLayout.createSequentialGroup()
                                        .addComponent(i_noId, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(i_jenisNoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(i_maksPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(i_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(i_telp, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(i_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrasiPeminjamLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(b_kosongkanRegPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b_simpanRegPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrasiPeminjamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_simpanPeminjamEmptyIndicator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        registrasiPeminjamLayout.setVerticalGroup(
            registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrasiPeminjamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(regisPeminjamTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_noId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i_jenisNoId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i_noId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_telp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i_telp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l_maksPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i_maksPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(l_simpanPeminjamEmptyIndicator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_simpanRegPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_kosongkanRegPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        l_nama.getAccessibleContext().setAccessibleName("");
        l_nama.getAccessibleContext().setAccessibleDescription("");
        i_nama.getAccessibleContext().setAccessibleName("");
        i_nama.getAccessibleContext().setAccessibleDescription("");
        l_noId.getAccessibleContext().setAccessibleName("");
        l_noId.getAccessibleContext().setAccessibleDescription("");
        i_noId.getAccessibleContext().setAccessibleName("");
        i_noId.getAccessibleContext().setAccessibleDescription("");
        i_jenisNoId.getAccessibleContext().setAccessibleName("");
        i_jenisNoId.getAccessibleContext().setAccessibleDescription("");
        l_alamat.getAccessibleContext().setAccessibleName("");
        l_alamat.getAccessibleContext().setAccessibleDescription("");
        i_alamat.getAccessibleContext().setAccessibleName("");
        i_alamat.getAccessibleContext().setAccessibleDescription("");
        l_telp.getAccessibleContext().setAccessibleName("");
        l_telp.getAccessibleContext().setAccessibleDescription("");
        i_telp.getAccessibleContext().setAccessibleName("");
        i_telp.getAccessibleContext().setAccessibleDescription("");
        l_maksPinjam.getAccessibleContext().setAccessibleName("");
        l_maksPinjam.getAccessibleContext().setAccessibleDescription("");
        i_maksPinjam.getAccessibleContext().setAccessibleName("");
        i_maksPinjam.getAccessibleContext().setAccessibleDescription("");

        formContainer.add(registrasiPeminjam, "card1");

        registrasiKoleksi.setMaximumSize(new java.awt.Dimension(150, 25));
        registrasiKoleksi.setMinimumSize(new java.awt.Dimension(150, 25));

        registKoleksiTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registKoleksiTitle.setText("Registrasi Data Koleksi");

        l_judulKoleksi.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_judulKoleksi.setText("Judul / Title");
        l_judulKoleksi.setMaximumSize(new java.awt.Dimension(150, 25));
        l_judulKoleksi.setMinimumSize(new java.awt.Dimension(150, 25));

        i_judulKoleksi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_judulKoleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_judulKoleksiActionPerformed(evt);
            }
        });

        l_penerbit.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_penerbit.setText("Penerbit");
        l_penerbit.setMaximumSize(new java.awt.Dimension(150, 25));
        l_penerbit.setMinimumSize(new java.awt.Dimension(150, 25));

        i_penerbit.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_penerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_penerbitActionPerformed(evt);
            }
        });

        l_judulBuku4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_judulBuku4.setText("Tipe Koleksi");
        l_judulBuku4.setMaximumSize(new java.awt.Dimension(150, 25));
        l_judulBuku4.setMinimumSize(new java.awt.Dimension(150, 25));

        inp_regTipeKoleksi.add(i_jenisBuku);
        i_jenisBuku.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        i_jenisBuku.setSelected(true);
        i_jenisBuku.setText("Buku");
        i_jenisBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_jenisBukuActionPerformed(evt);
            }
        });

        inp_regTipeKoleksi.add(i_jenisMajalah);
        i_jenisMajalah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        i_jenisMajalah.setText("Majalah");
        i_jenisMajalah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_jenisMajalahActionPerformed(evt);
            }
        });

        inp_regTipeKoleksi.add(i_jenisDisk);
        i_jenisDisk.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        i_jenisDisk.setText("Disk");
        i_jenisDisk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_jenisDiskActionPerformed(evt);
            }
        });

        l_isbnIssn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_isbnIssn.setText("ISBN / ISSN");
        l_isbnIssn.setMaximumSize(new java.awt.Dimension(150, 25));
        l_isbnIssn.setMinimumSize(new java.awt.Dimension(150, 25));

        i_isbnIssn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_isbnIssn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                i_isbnIssnFocusLost(evt);
            }
        });
        i_isbnIssn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_isbnIssnActionPerformed(evt);
            }
        });

        l_jmlHalaman.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_jmlHalaman.setText("Jml. Halaman");
        l_jmlHalaman.setMaximumSize(new java.awt.Dimension(150, 25));
        l_jmlHalaman.setMinimumSize(new java.awt.Dimension(150, 25));

        i_jmlHalaman.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        i_jmlHalaman.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        l_volume.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_volume.setText("Volume");
        l_volume.setEnabled(false);
        l_volume.setMaximumSize(new java.awt.Dimension(150, 25));
        l_volume.setMinimumSize(new java.awt.Dimension(150, 25));

        i_volume.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        i_volume.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        i_volume.setEnabled(false);

        l_seri.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_seri.setText("Seri");
        l_seri.setEnabled(false);
        l_seri.setMaximumSize(new java.awt.Dimension(150, 25));
        l_seri.setMinimumSize(new java.awt.Dimension(150, 25));

        i_seri.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        i_seri.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        i_seri.setEnabled(false);

        l_format.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_format.setText("Format");
        l_format.setEnabled(false);
        l_format.setMaximumSize(new java.awt.Dimension(150, 25));
        l_format.setMinimumSize(new java.awt.Dimension(150, 25));

        i_format.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Audio", "Video", "Multimedia" }));
        i_format.setEnabled(false);
        i_format.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_formatActionPerformed(evt);
            }
        });

        b_simpanRegKoleksi.setBackground(new java.awt.Color(51, 204, 0));
        b_simpanRegKoleksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_simpanRegKoleksi.setForeground(new java.awt.Color(255, 255, 255));
        b_simpanRegKoleksi.setText("Simpan");
        b_simpanRegKoleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_simpanRegKoleksiActionPerformed(evt);
            }
        });

        b_kosongkanRegKoleksi.setBackground(new java.awt.Color(255, 102, 102));
        b_kosongkanRegKoleksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_kosongkanRegKoleksi.setForeground(new java.awt.Color(255, 255, 255));
        b_kosongkanRegKoleksi.setText("Kosongkan");
        b_kosongkanRegKoleksi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b_kosongkanRegKoleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_kosongkanRegKoleksiActionPerformed(evt);
            }
        });

        l_simpanKoleksiEmptyIndicator.setBackground(new java.awt.Color(153, 153, 153));
        l_simpanKoleksiEmptyIndicator.setForeground(new java.awt.Color(255, 51, 51));
        l_simpanKoleksiEmptyIndicator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_simpanKoleksiEmptyIndicator.setText("Terdapat data yang masih kosong atau tidak benar!");
        l_simpanKoleksiEmptyIndicator.setVisible(false);

        javax.swing.GroupLayout registrasiKoleksiLayout = new javax.swing.GroupLayout(registrasiKoleksi);
        registrasiKoleksi.setLayout(registrasiKoleksiLayout);
        registrasiKoleksiLayout.setHorizontalGroup(
            registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrasiKoleksiLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrasiKoleksiLayout.createSequentialGroup()
                        .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registKoleksiTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(registrasiKoleksiLayout.createSequentialGroup()
                                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(l_penerbit, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(l_isbnIssn, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(l_judulBuku4, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(l_jmlHalaman, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(l_volume, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(l_judulKoleksi, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                    .addComponent(l_seri, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_format, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(registrasiKoleksiLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(i_judulKoleksi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(i_jenisBuku)
                                                    .addComponent(i_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(i_jenisMajalah)
                                                    .addComponent(i_jenisDisk)
                                                    .addComponent(i_isbnIssn, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(i_jmlHalaman, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(i_volume, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(i_seri, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(registrasiKoleksiLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(i_format, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(133, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrasiKoleksiLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(b_kosongkanRegKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b_simpanRegKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrasiKoleksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_simpanKoleksiEmptyIndicator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        registrasiKoleksiLayout.setVerticalGroup(
            registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrasiKoleksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registKoleksiTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(i_judulKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_judulKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(i_isbnIssn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_isbnIssn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(i_jenisBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_judulBuku4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(i_jenisMajalah, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(i_jenisDisk, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrasiKoleksiLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(i_jmlHalaman, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(l_jmlHalaman, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrasiKoleksiLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(i_volume, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(l_volume, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_seri, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i_seri, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_format, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i_format, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(l_simpanKoleksiEmptyIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_simpanRegKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_kosongkanRegKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        formContainer.add(registrasiKoleksi, "card2");

        menuBarMain.setForeground(new java.awt.Color(153, 204, 255));

        menuBar_tambah.setText("Tambah");

        tambahPeminjam.setText("Peminjam baru");
        tambahPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPeminjamActionPerformed(evt);
            }
        });
        menuBar_tambah.add(tambahPeminjam);

        tambahKoleksi.setText("Koleksi baru");
        tambahKoleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahKoleksiActionPerformed(evt);
            }
        });
        menuBar_tambah.add(tambahKoleksi);

        menuBarMain.add(menuBar_tambah);

        menuBar_edit.setText("Edit");

        editPeminjam.setText("Peminjam");
        editPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPeminjamActionPerformed(evt);
            }
        });
        menuBar_edit.add(editPeminjam);

        editKoleksi.setText("Koleksi");
        menuBar_edit.add(editKoleksi);

        menuBarMain.add(menuBar_edit);

        menuBar_transaksi.setText("Transaksi");

        transaksiPinjam.setText("Pinjam");
        menuBar_transaksi.add(transaksiPinjam);

        transaksiKembali.setText("Kembali");
        menuBar_transaksi.add(transaksiKembali);

        menuBarMain.add(menuBar_transaksi);

        menuBar_koleksi.setText("Koleksi");

        koleksiBuku.setText("Buku");
        menuBar_koleksi.add(koleksiBuku);

        koleksiMajalah.setText("Majalah");
        koleksiMajalah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                koleksiMajalahActionPerformed(evt);
            }
        });
        menuBar_koleksi.add(koleksiMajalah);

        koleksiDisk.setText("Disk");
        menuBar_koleksi.add(koleksiDisk);

        menuBarMain.add(menuBar_koleksi);

        menuBar_informasi.setText("Informasi");
        menuBarMain.add(menuBar_informasi);

        menuBar_keluar.setText("Keluar");

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        menuBar_keluar.add(logout);

        menuBarMain.add(menuBar_keluar);

        setJMenuBar(menuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(menuContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(formContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Mengganti frame formulir ke formulir registrasi data peminjam menggunakan container {@link CardLayout} (formCards).
     * */
    private void b_regPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_regPeminjamActionPerformed
        formCards.show(formContainer, "card1");
    }//GEN-LAST:event_b_regPeminjamActionPerformed

    /**
     * Mengganti frame formulir ke formulir registrasi data koleksi menggunakan container {@link CardLayout} (formCards).
     * */
    private void b_regKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_regKoleksiActionPerformed
        formCards.show(formContainer, "card2");
    }//GEN-LAST:event_b_regKoleksiActionPerformed

    /**
     * Mengosongkan dan mengatur nilai ke awal pada formulir registrasi data peminjam.
     * */
    private void b_kosongkanRegPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_kosongkanPeminjamActionPerformed
        kosongkanRegPeminjam();                                 // panggil metode yang mengosongkan reg. peminjam
        
        l_simpanPeminjamEmptyIndicator.setVisible(false);       // mematikan indikator field masih kosong
    }//GEN-LAST:event_b_kosongkanPeminjamActionPerformed

    /**
     * Mengimpan data dan menampilkan dialog {@link RegistrasiPeminjamBerhasil}  dengan data yang dikirim.
     * */
    private void b_simpanRegPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_simpanPeminjamBaruActionPerformed
        /* Variabel-variabel penyimpan data */
        String nama = i_nama.getText().trim();
        String noId = i_noId.getText().trim();
        String jenisNoId = (String) i_jenisNoId.getSelectedItem();
        String alamat = i_alamat.getText().trim();
        String noTelp = i_telp.getText().trim();
        int maksPinjam = (int) i_maksPinjam.getValue();

        /* mengecek apakah terdapat field yang kosong setelah ditrim untuk setiap field String */
        for (String field : new String[] {nama, noId, jenisNoId, alamat, noTelp}) {
            if (checkIsEmpty(field)) {
                l_simpanPeminjamEmptyIndicator.setVisible(true);
                return;
            }
        }
        /* mengecek apakah format nomor identitas dan telepon sudah valid*/
        if (!Checker.isNomor(noId) && !Checker.isNomor(noTelp)) {
            l_simpanPeminjamEmptyIndicator.setVisible(true);
            return;
        }
        l_simpanPeminjamEmptyIndicator.setVisible(false);

        /* mengeksekusi pembuatan dialog data dengan antrian event tasks */
        java.awt.EventQueue.invokeLater(
          () -> new RegistrasiPeminjamBerhasil(this, true, nama, noId, jenisNoId, alamat, noTelp, maksPinjam)
            .setVisible(true)
        );
        kosongkanRegPeminjam();

        /* Print data */
        System.out.printf("""
          Saved peminjam baru: {
            nama: "%s",
            noId: "%s",
            jenisNoId: "%s",
            alamat: "%s",
            telp: "%s",
            maksPinjam: %1d
          }
          """,
          nama, noId, jenisNoId, alamat, noTelp, maksPinjam);
    }//GEN-LAST:event_b_simpanPeminjamBaruActionPerformed

    private void i_telpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_telpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_telpActionPerformed

    private void i_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_alamatActionPerformed

    private void i_jenisNoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_jenisNoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_jenisNoIdActionPerformed

    private void i_noIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_noIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_noIdActionPerformed

    private void i_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_namaActionPerformed

    /**
     * Mengosongkan dan mengatur nilai ke awal pada formulir registrasi data koleksi.
     * */
    private void b_kosongkanRegKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlKosongkanActionPerformed
        kosongkanRegKoleksi();                              // panggil metode yang mengosongkan reg. peminjam

        l_simpanKoleksiEmptyIndicator.setVisible(false);    // mematikan indikator field masih kosong
    }//GEN-LAST:event_btlKosongkanActionPerformed

    /**
     * Mengimpan data dan menampilkan dialog {@link RegistrasiKoleksiBerhasil} dengan data yang dikirim.
     * */
    private void b_simpanRegKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanBukuActionPerformed
        /* Variabel-variabel penyimpan data */
        String judul = i_judulKoleksi.getText().trim();
        String penerbit = i_penerbit.getText().trim();
        String isbnIssn = i_isbnIssn.getText().trim();

        String tipeKoleksi = "";
        /* Melakukan iterasi setiap button pada button group, mencari button yang dipilih. */
        for (Enumeration<AbstractButton> bg = inp_regTipeKoleksi.getElements(); bg.hasMoreElements();) {
            AbstractButton b = bg.nextElement();

            if (b.isSelected()) {
                tipeKoleksi = b.getText();
                break;
            }
        };

        /* Variabel-variabel penyimpan data (2) */
        int jmlHalaman = (int) i_jmlHalaman.getValue();
        int volume = (int) i_volume.getValue();
        int seri = (int) i_seri.getValue();
        String format = (String) i_format.getSelectedItem();

        /* mengecek apakah terdapat field yang kosong setelah ditrim */
        for (String field : new String[] {judul, penerbit, isbnIssn}) {
            if (checkIsEmpty(field)) {
                l_simpanKoleksiEmptyIndicator.setVisible(true);
                return;
            }
        }
        /* mengecek apakah format isbn sudah valid*/
        if (!Checker.isNomorSpaceHyphen(isbnIssn)) {
            l_simpanKoleksiEmptyIndicator.setVisible(true);
            return;
        }
        l_simpanKoleksiEmptyIndicator.setVisible(false);

        final String finalTipeKoleksi = tipeKoleksi;
        switch (tipeKoleksi) {
            case "Buku" -> EventQueue.invokeLater(
              () -> new RegistrasiKoleksiBerhasil(this, true)
                .isiField(finalTipeKoleksi, judul, penerbit, isbnIssn, jmlHalaman)
                .setVisible(true)
            );
            case "Majalah" -> EventQueue.invokeLater(
              () -> new RegistrasiKoleksiBerhasil(this, true)
                .isiField(finalTipeKoleksi, judul, penerbit, isbnIssn, volume, seri)
                .setVisible(true)
            );
            default -> EventQueue.invokeLater(
              () -> new RegistrasiKoleksiBerhasil(this, true)
                .isiField(finalTipeKoleksi, judul, penerbit, isbnIssn, format)
                .setVisible(true)
            );
        }
        kosongkanRegKoleksi();

        /* Print data */
        System.out.printf("""
          Saved koleksi baru: {
            judul: "%s",
            penerbit: "%s",
            isbnIssn: "%s",
            tipeKoleksi: "%s",
            jmlHalaman: %1d,
            volume: %1d,
            seri: %1d,
            format: "%s"
          }
          """,
          judul, penerbit, isbnIssn, tipeKoleksi, jmlHalaman, volume, seri, format);
    }//GEN-LAST:event_btnSimpanBukuActionPerformed

    private void i_isbnIssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_isbnIssnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_isbnIssnActionPerformed

    /**
     * Mengaktifkan input field disk (label dan input: FORMAT)
     * */
    private void i_jenisDiskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_jenisDiskActionPerformed
        setFalseAllTipeKoleksi();                               // mematikan semua fields spesifik

        /* Menyalakan label dan input yang relevan dengan tipe koleksinya. l: Label, i: Input.*/
        l_format.setEnabled(true);
        i_format.setEnabled(true);
    }//GEN-LAST:event_i_jenisDiskActionPerformed

    /**
     * Mengaktifkan input field majalah (label dan input: VOLUME, SERI).
     * */
    private void i_jenisMajalahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_jenisMajalahActionPerformed
        setFalseAllTipeKoleksi();                               // mematikan semua fields spesifik

        /* Menyalakan label dan input yang relevan dengan tipe koleksinya. l: Label, i: Input.*/
        l_volume.setEnabled(true);
        i_volume.setEnabled(true);
        l_seri.setEnabled(true);
        i_seri.setEnabled(true);
    }//GEN-LAST:event_i_jenisMajalahActionPerformed

    /**
     * Mengaktifkan input field buku (label dan input: HALAMAN).
     * */
    private void i_jenisBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_jenisBukuActionPerformed
        setFalseAllTipeKoleksi();                               // mematikan semua fields spesifik

        /* Menyalakan label dan input yang relevan dengan tipe koleksinya. l: Label, i: Input.*/
        l_jmlHalaman.setEnabled(true);
        i_jmlHalaman.setEnabled(true);
    }//GEN-LAST:event_i_jenisBukuActionPerformed

    private void i_penerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_penerbitActionPerformed
    }//GEN-LAST:event_i_penerbitActionPerformed

    private void i_judulKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_judulKoleksiActionPerformed
    }//GEN-LAST:event_i_judulKoleksiActionPerformed

    private void editPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPeminjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editPeminjamActionPerformed

    private void koleksiMajalahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_koleksiMajalahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_koleksiMajalahActionPerformed

    /**
     * Mengganti formulir ke registrasi peminjam dengan container {@link CardLayout} (formContainer).
     * */
    private void tambahPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPeminjamActionPerformed
        formCards.show(formContainer, "card1");
    }//GEN-LAST:event_tambahPeminjamActionPerformed

    /**
     * Mengganti formulir ke registrasi koleksi dengan container {@link CardLayout} (formContainer).
     * */
    private void tambahKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahKoleksiActionPerformed
        formCards.show(formContainer, "card2");
    }//GEN-LAST:event_tambahKoleksiActionPerformed

    /**
     * Membuang {@link App} ini jika {@link App#homePage} sudah diatur. Membuka frame {@link App#homePage}.
     * */
    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        if (homePage != null) {
            this.dispose();
            homePage.setVisible(true);
        } else {
            System.out.println("Home page tidak di inisialisasi.");
            // belum ada
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void i_formatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_formatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_formatActionPerformed

    private void i_telpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_i_telpFocusLost
        if (!Checker.isNomor(i_telp.getText())) {
            i_telp.setBackground(new Color(0xFF5959));
        } else {
            i_telp.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_i_telpFocusLost

    private void i_noIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_i_noIdFocusLost
        if (!Checker.isNomor(i_noId.getText())) {
            i_noId.setBackground(new Color(0xFF5959));
        } else {
            i_noId.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_i_noIdFocusLost

    private void i_isbnIssnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_i_isbnIssnFocusLost
        if (!Checker.isNomorSpaceHyphen(i_isbnIssn.getText())) {
            i_isbnIssn.setBackground(new Color(0xFF5959));
        } else {
            i_isbnIssn.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_i_isbnIssnFocusLost

    /* Other functions */

    /**
     * Menyetel seluruh fields spesial dalam formulir registrasi koleksi ke mati (disabled).
     * */
    private void setFalseAllTipeKoleksi() {
        l_jmlHalaman.setEnabled(false);
        i_jmlHalaman.setEnabled(false);
        l_volume.setEnabled(false);
        i_volume.setEnabled(false);
        l_seri.setEnabled(false);
        i_seri.setEnabled(false);
        l_format.setEnabled(false);
        i_format.setEnabled(false);
    }

    /** Mengosongkan/mengatur seluruh field registrasi peminjam dengan nilai awal. */
    private void kosongkanRegPeminjam() {
        i_nama.setText("");
        i_noId.setText("");
        i_jenisNoId.setSelectedIndex(0);
        i_alamat.setText("");
        i_telp.setText("");
        i_maksPinjam.setValue(1);
    }

    /** Mengosongkan/mengatur seluruh field registrasi koleksi dengan nilai awal. */
    private void kosongkanRegKoleksi() {
        i_judulKoleksi.setText("");
        i_penerbit.setText("");
        i_isbnIssn.setText("");

        /* Memilih pilihan "Buku" dan mematikan kolom input spesifik lain kecuali jumlah halaman */
        inp_regTipeKoleksi.setSelected(i_jenisBuku.getModel(), true);
        setFalseAllTipeKoleksi();
        l_jmlHalaman.setEnabled(true);
        i_jmlHalaman.setEnabled(true);

        i_jmlHalaman.setValue(1);
        i_volume.setValue(1);
        i_seri.setValue(1);
        i_format.setSelectedIndex(0);
    }

    /**
     * Mengecek apakah sebuah {@link String} kosong setelah dilakukan trimming.
     *
     * @return boolean true atau false
     * */
    private boolean checkIsEmpty(String str) {
        return str.trim().equals("");
    }

    /**
     * Metode penjalan kelas.
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        try {
            /* Mengatur look and feels tampilan jendela menjadi Nimbus */
            javax.swing.UIManager.setLookAndFeel(new javax.swing.plaf.nimbus.NimbusLookAndFeel());
            /* Mengantrikan aplikasi ke event queue */
            java.awt.EventQueue.invokeLater(() -> new App().setVisible(true));
        } catch (UnsupportedLookAndFeelException ex) {          // catch error saat look and feel tidak ditemukan
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_kosongkanRegKoleksi;
    private javax.swing.JButton b_kosongkanRegPeminjam;
    private javax.swing.JButton b_regKoleksi;
    private javax.swing.JButton b_regPeminjam;
    private javax.swing.JButton b_simpanRegKoleksi;
    private javax.swing.JButton b_simpanRegPeminjam;
    private javax.swing.JMenuItem editKoleksi;
    private javax.swing.JMenuItem editPeminjam;
    private javax.swing.JPanel formContainer;
    private java.awt.TextField i_alamat;
    private javax.swing.JComboBox<String> i_format;
    private java.awt.TextField i_isbnIssn;
    private javax.swing.JRadioButton i_jenisBuku;
    private javax.swing.JRadioButton i_jenisDisk;
    private javax.swing.JRadioButton i_jenisMajalah;
    private javax.swing.JComboBox<String> i_jenisNoId;
    private javax.swing.JSpinner i_jmlHalaman;
    private java.awt.TextField i_judulKoleksi;
    private javax.swing.JSpinner i_maksPinjam;
    private java.awt.TextField i_nama;
    private java.awt.TextField i_noId;
    private java.awt.TextField i_penerbit;
    private javax.swing.JSpinner i_seri;
    private java.awt.TextField i_telp;
    private javax.swing.JSpinner i_volume;
    private javax.swing.ButtonGroup inp_regTipeKoleksi;
    private javax.swing.JMenuItem koleksiBuku;
    private javax.swing.JMenuItem koleksiDisk;
    private javax.swing.JMenuItem koleksiMajalah;
    private javax.swing.JLabel l_alamat;
    private javax.swing.JLabel l_format;
    private javax.swing.JLabel l_isbnIssn;
    private javax.swing.JLabel l_jmlHalaman;
    private javax.swing.JLabel l_judulBuku4;
    private javax.swing.JLabel l_judulKoleksi;
    private javax.swing.JLabel l_logoSadhar;
    private javax.swing.JLabel l_maksPinjam;
    private javax.swing.JLabel l_nama;
    private javax.swing.JLabel l_noId;
    private javax.swing.JLabel l_penerbit;
    private javax.swing.JLabel l_seri;
    private javax.swing.JLabel l_simpanKoleksiEmptyIndicator;
    private javax.swing.JLabel l_simpanPeminjamEmptyIndicator;
    private javax.swing.JLabel l_telp;
    private javax.swing.JLabel l_volume;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenuBar menuBarMain;
    private javax.swing.JMenu menuBar_edit;
    private javax.swing.JMenu menuBar_informasi;
    private javax.swing.JMenu menuBar_keluar;
    private javax.swing.JMenu menuBar_koleksi;
    private javax.swing.JMenu menuBar_tambah;
    private javax.swing.JMenu menuBar_transaksi;
    private javax.swing.JPanel menuContainer;
    private javax.swing.JLabel menuTitle;
    private javax.swing.JLabel regisPeminjamTitle;
    private javax.swing.JLabel registKoleksiTitle;
    private javax.swing.JPanel registrasiKoleksi;
    private javax.swing.JPanel registrasiPeminjam;
    private javax.swing.JMenuItem tambahKoleksi;
    private javax.swing.JMenuItem tambahPeminjam;
    private javax.swing.JMenuItem transaksiKembali;
    private javax.swing.JMenuItem transaksiPinjam;
    // End of variables declaration//GEN-END:variables
}
