/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

import javax.swing.*;

/**
 *
 * @author narwa
 */
public class RegistrasiKoleksiBerhasil extends javax.swing.JDialog {

    /**
     * Creates new form RegistrasiPeminjamBerhasil
     */
    public RegistrasiKoleksiBerhasil(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_regPeminjamBerhasil = new javax.swing.JDialog();
        l_frameTitle = new javax.swing.JLabel();
        b_regBerhasilOk = new javax.swing.JButton();
        l_savedJudul = new javax.swing.JLabel();
        f_savedJudul = new javax.swing.JLabel();
        l_savedPenerbit = new javax.swing.JLabel();
        f_savedIsbnIssn = new javax.swing.JLabel();
        l_savedIsbnIssn = new javax.swing.JLabel();
        f_tipeKoleksi = new javax.swing.JLabel();
        l_savedTipeKoleksi = new javax.swing.JLabel();
        f_savedPenerbit = new javax.swing.JLabel();
        f_specific1 = new javax.swing.JLabel();
        l_specific1 = new javax.swing.JLabel();
        f_specific2 = new javax.swing.JLabel();
        l_specific2 = new javax.swing.JLabel();

        dialog_regPeminjamBerhasil.setTitle("Registrasi berhasil");
        dialog_regPeminjamBerhasil.setResizable(false);

        javax.swing.GroupLayout dialog_regPeminjamBerhasilLayout = new javax.swing.GroupLayout(dialog_regPeminjamBerhasil.getContentPane());
        dialog_regPeminjamBerhasil.getContentPane().setLayout(dialog_regPeminjamBerhasilLayout);
        dialog_regPeminjamBerhasilLayout.setHorizontalGroup(
            dialog_regPeminjamBerhasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        );
        dialog_regPeminjamBerhasilLayout.setVerticalGroup(
            dialog_regPeminjamBerhasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrasi Peminjam Berhasil");
        setPreferredSize(new java.awt.Dimension(661, 180));
        setResizable(false);

        l_frameTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        l_frameTitle.setText("Registrasi Koleksi Berhasil");

        b_regBerhasilOk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_regBerhasilOk.setText("Ok");
        b_regBerhasilOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_regBerhasilOkActionPerformed(evt);
            }
        });

        l_savedJudul.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        l_savedJudul.setText("Judul");

        f_savedJudul.setText("n");
        f_savedJudul.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        l_savedPenerbit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        l_savedPenerbit.setText("Penerbit");

        f_savedIsbnIssn.setText("n");
        f_savedIsbnIssn.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        l_savedIsbnIssn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        l_savedIsbnIssn.setText("ISBN / ISSN");

        f_tipeKoleksi.setText("n");
        f_tipeKoleksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        l_savedTipeKoleksi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        l_savedTipeKoleksi.setText("Tipe Koleksi");

        f_savedPenerbit.setText("n");
        f_savedPenerbit.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        f_specific1.setText("n");
        f_specific1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        l_specific1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        l_specific1.setText("specific1");

        f_specific2.setText("n");
        f_specific2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        l_specific2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        l_specific2.setText("specific2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l_savedJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(f_savedJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l_savedPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(f_savedPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l_savedIsbnIssn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(f_savedIsbnIssn, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(l_frameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b_regBerhasilOk, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(l_savedTipeKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(f_tipeKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(l_specific1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(f_specific1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(l_specific2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(f_specific2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_frameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_savedJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f_savedJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_savedPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f_savedPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_savedIsbnIssn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f_savedIsbnIssn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(l_savedTipeKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(f_tipeKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(l_specific1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(f_specific1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(l_specific2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(f_specific2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(b_regBerhasilOk)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Menutup dialog. */
    private void b_regBerhasilOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_regBerhasilOkActionPerformed
        dispose();
    }//GEN-LAST:event_b_regBerhasilOkActionPerformed

    /** Mengatur field tipeKoleksi Buku. */
    public RegistrasiKoleksiBerhasil isiField(String tipeKoleksi, String judul, String penerbit, String isbn, int jmlHalaman) {
        l_frameTitle.setText("Registrasi " + tipeKoleksi + " Berhasil");

        f_savedJudul.setText(judul);
        f_savedPenerbit.setText(penerbit);
        l_savedIsbnIssn.setText("ISBN");
        f_savedIsbnIssn.setText(isbn);
        l_specific1.setText("Jml. Halaman");
        f_specific1.setText(String.valueOf(jmlHalaman));
        l_specific2.setVisible(false);
        f_specific2.setVisible(false);
        return this;
    }

    /** Mengatur field tipeKoleksi Majalah. */
    public RegistrasiKoleksiBerhasil isiField(String tipeKoleksi, String judul, String penerbit, String isbn, int volume, int seri) {
        l_frameTitle.setText("Registrasi " + tipeKoleksi + " Berhasil");

        f_savedJudul.setText(judul);
        f_savedPenerbit.setText(penerbit);
        l_savedIsbnIssn.setText("ISBN");
        f_savedIsbnIssn.setText(isbn);
        l_specific1.setText("Volume");
        f_specific1.setText(String.valueOf(volume));
        l_specific2.setText("Seri");
        f_specific2.setText(String.valueOf(seri));
        return this;
    }
    /** Mengatur field tipeKoleksi Dsik. */
    public RegistrasiKoleksiBerhasil isiField(String tipeKoleksi, String judul, String penerbit, String isbn, String format) {
        l_frameTitle.setText("Registrasi " + tipeKoleksi + " Berhasil");

        f_savedJudul.setText(judul);
        f_savedPenerbit.setText(penerbit);
        l_savedIsbnIssn.setText("ISBN");
        f_savedIsbnIssn.setText(isbn);
        l_specific1.setText("Format");
        f_specific1.setText(format);

        l_specific2.setVisible(false);
        f_specific2.setVisible(false);
        return this;
    }
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | UnsupportedLookAndFeelException | InstantiationException |
                 IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrasiPeminjamBerhasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistrasiPeminjamBerhasil dialog = new RegistrasiPeminjamBerhasil(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_regBerhasilOk;
    private javax.swing.JDialog dialog_regPeminjamBerhasil;
    private javax.swing.JLabel f_savedIsbnIssn;
    private javax.swing.JLabel f_savedJudul;
    private javax.swing.JLabel f_savedPenerbit;
    private javax.swing.JLabel f_specific1;
    private javax.swing.JLabel f_specific2;
    private javax.swing.JLabel f_tipeKoleksi;
    private javax.swing.JLabel l_frameTitle;
    private javax.swing.JLabel l_savedIsbnIssn;
    private javax.swing.JLabel l_savedJudul;
    private javax.swing.JLabel l_savedPenerbit;
    private javax.swing.JLabel l_savedTipeKoleksi;
    private javax.swing.JLabel l_specific1;
    private javax.swing.JLabel l_specific2;
    // End of variables declaration//GEN-END:variables
}
