import backend.*;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * @author narwa
 */
public class App extends javax.swing.JFrame {
	/**
	 * Atribut kelas ini menyimpan data dari data perpustakaan.
	 * */
	public DataPerpus dataPerpus;

    private final CardLayout formCards;
    private final HomePage homePage;

	/**
	 * Default constructor tanpa home page (landing page).
	 */
	public App() {
		/* Untuk tes: (tidak memiliki referensi HomePage) */
		this.homePage = null;
		initComponents();
		setTitle("Sistem Manajemen Perpustakaan");

		/* Mengatur icon/gambar judul pada window frame */
		setIconImage(
			new ImageIcon(
				Objects.requireNonNull(
					getClass().getResource("/images/bookIcon.png"))
			).getImage()
		);
        initForms();
		fillPeminjam(); // TODO: Hapus filler

		/* Menyimpan format CardLayout untuk berpindah card panel */
		formCards = (CardLayout) formContainer.getLayout();
	}

	/**
	 * Constructor dengan home page (landing page).
	 */
	public App(HomePage homePage) {
		/* Referensi HomePage untuk melakukan log out */
		this.homePage = homePage;
		this.dataPerpus = new DataPerpus();
		initComponents();
		setTitle("Sistem Manajemen Perpustakaan");

		/* Mengatur icon/gambar judul pada window frame */
		setIconImage(
			new ImageIcon(
				Objects.requireNonNull(
					getClass().getResource("/images/bookIcon.png"))
			).getImage()
		);
		fillPeminjam();
		fillKoleksi();
        initForms(); // TODO: Hapus filler

		/* Menyimpan format CardLayout untuk berpindah card panel */
		formCards = (CardLayout) formContainer.getLayout();
	}

	protected void fillPeminjam() {
		System.out.println("Filling list of customers with test data...");
		dataPerpus.isiDataPeminjam(new Dosen("D00001", "Dosen1", "NIP", "Paingan Yogyakarta", "012345678911", 3, "123456781234567801"));
		dataPerpus.isiDataPeminjam(new Dosen("D00002", "Dosen2", "NIP", "Depok Yogyakarta", "012345678912", 1, "123456781234567802"));
		dataPerpus.isiDataPeminjam(new Dosen("D00003", "Dosen3", "NIP", "Klaten Yogyakarta", "012345678913", 4, "123456781234567803"));
		dataPerpus.isiDataPeminjam(new Mahasiswa("M00001", "Mahasiswa1", "NIM", "Bantul Something", "012345678921", 3, "225314001"));
		dataPerpus.isiDataPeminjam(new Mahasiswa("M00002", "Mahasiswa2", "NIM", "Bekasi Something", "012345678922", 5, "225314002"));
		dataPerpus.isiDataPeminjam(new Umum("U00001", "Umum1", "NIK", "Kaliurang Something", "012345678930", 5, "2253140021234567"));

		for (var c : dataPerpus.getListPeminjam()) {
			System.out.println(c);
		}
	}

	protected void fillKoleksi() {
		System.out.println("Filling list of koleksi with test data...");
		dataPerpus.isiDataKoleksi(new Buku("B00001", "Buku", "CORP", "1950", "1234567890001", 3));
		dataPerpus.isiDataKoleksi(new Majalah("M00002", "Majalah", "INC", "1945", "1234567890002", 1, 2));

		for (var k : dataPerpus.getListKoleksi()) {
			System.out.println(k);
		}
	}

    /**
     *  Melakukan insialisasi panel panel form
     * */
    private void initForms() {
		JPanel formRegistrasiPeminjam = new FormRegistrasiPeminjam(this, dataPerpus);
		JPanel formRegistrasiKoleksi = new FormRegistrasiKoleksi(this, dataPerpus);

        formContainer.add(formRegistrasiPeminjam, "card1");
        formContainer.add(formRegistrasiKoleksi, "card2");
    }

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inp_regTipeKoleksi = new javax.swing.ButtonGroup();
        menuContainer = new javax.swing.JPanel();
        menuTitle = new javax.swing.JLabel();
        b_regPeminjam = new javax.swing.JButton();
        b_regKoleksi = new javax.swing.JButton();
        l_logoSadhar = new javax.swing.JLabel();
        formContainer = new javax.swing.JPanel();
        menuBarMain = new javax.swing.JMenuBar();
        menuBar_tambah = new javax.swing.JMenu();
        tambahPeminjam = new javax.swing.JMenuItem();
        tambahKoleksi = new javax.swing.JMenuItem();
        menuBar_edit = new javax.swing.JMenu();
        editPeminjam = new javax.swing.JMenuItem();
        editKoleksi = new javax.swing.JMenuItem();
        menuBar_transaksi = new javax.swing.JMenu();
        transaksiPinjam = new javax.swing.JMenuItem();
        transaksiKembali = new javax.swing.JMenuItem();
        menuBar_koleksi = new javax.swing.JMenu();
        koleksiBuku = new javax.swing.JMenuItem();
        koleksiMajalah = new javax.swing.JMenuItem();
        koleksiDisk = new javax.swing.JMenuItem();
        menuBar_informasi = new javax.swing.JMenu();
        menuBar_keluar = new javax.swing.JMenu();
        logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Manajemen Data Perpustakaan");
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1280, 720));
        setMinimumSize(new java.awt.Dimension(960, 540));
        setResizable(false);

        menuContainer.setBackground(new java.awt.Color(153, 204, 255));

        menuTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuTitle.setForeground(new java.awt.Color(51, 102, 255));
        menuTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTitle.setText("<html>Sistem Manajemen<br/>Perpustakaan</html>");

        b_regPeminjam.setBackground(new java.awt.Color(153, 153, 255));
        b_regPeminjam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_regPeminjam.setForeground(new java.awt.Color(255, 255, 255));
        b_regPeminjam.setText("Registrasi Peminjam");
        b_regPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_regPeminjamActionPerformed(evt);
            }
        });

        b_regKoleksi.setBackground(new java.awt.Color(153, 153, 255));
        b_regKoleksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_regKoleksi.setForeground(new java.awt.Color(255, 255, 255));
        b_regKoleksi.setText("Registrasi Koleksi");
        b_regKoleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_regKoleksiActionPerformed(evt);
            }
        });

        l_logoSadhar.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoSanataDharma.png")).getImage().getScaledInstance(180, 180, Image.SCALE_SMOOTH)));

        javax.swing.GroupLayout menuContainerLayout = new javax.swing.GroupLayout(menuContainer);
        menuContainer.setLayout(menuContainerLayout);
        menuContainerLayout.setHorizontalGroup(
            menuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuTitle)
                    .addComponent(b_regPeminjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_regKoleksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_logoSadhar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        menuContainerLayout.setVerticalGroup(
            menuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_regPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_regKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_logoSadhar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        formContainer.setBackground(new java.awt.Color(255, 255, 255));
        formContainer.setLayout(new java.awt.CardLayout());

        menuBarMain.setForeground(new java.awt.Color(153, 204, 255));

        menuBar_tambah.setText("Tambah");

        tambahPeminjam.setText("Peminjam baru");
        tambahPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPeminjamActionPerformed(evt);
            }
        });
        menuBar_tambah.add(tambahPeminjam);

        tambahKoleksi.setText("Koleksi baru");
        tambahKoleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahKoleksiActionPerformed(evt);
            }
        });
        menuBar_tambah.add(tambahKoleksi);

        menuBarMain.add(menuBar_tambah);

        menuBar_edit.setText("Edit");

        editPeminjam.setText("Peminjam");
        editPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPeminjamActionPerformed(evt);
            }
        });
        menuBar_edit.add(editPeminjam);

        editKoleksi.setText("Koleksi");
        menuBar_edit.add(editKoleksi);

        menuBarMain.add(menuBar_edit);

        menuBar_transaksi.setText("Transaksi");

        transaksiPinjam.setText("Pinjam");
        menuBar_transaksi.add(transaksiPinjam);

        transaksiKembali.setText("Kembali");
        menuBar_transaksi.add(transaksiKembali);

        menuBarMain.add(menuBar_transaksi);

        menuBar_koleksi.setText("Koleksi");

        koleksiBuku.setText("Buku");
        menuBar_koleksi.add(koleksiBuku);

        koleksiMajalah.setText("Majalah");
        koleksiMajalah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                koleksiMajalahActionPerformed(evt);
            }
        });
        menuBar_koleksi.add(koleksiMajalah);

        koleksiDisk.setText("Disk");
        menuBar_koleksi.add(koleksiDisk);

        menuBarMain.add(menuBar_koleksi);

        menuBar_informasi.setText("Informasi");
        menuBarMain.add(menuBar_informasi);

        menuBar_keluar.setText("Keluar");

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        menuBar_keluar.add(logout);

        menuBarMain.add(menuBar_keluar);

        setJMenuBar(menuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(menuContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(formContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * Mengganti frame formulir ke formulir registrasi data peminjam menggunakan container {@link CardLayout} (formCards).
	 */
	private void b_regPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_regPeminjamActionPerformed
		formCards.show(formContainer, "card1");
	}//GEN-LAST:event_b_regPeminjamActionPerformed

	/**
	 * Mengganti frame formulir ke formulir registrasi data koleksi menggunakan container {@link CardLayout} (formCards).
	 */
	private void b_regKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_regKoleksiActionPerformed
		formCards.show(formContainer, "card2");
	}//GEN-LAST:event_b_regKoleksiActionPerformed

	private void editPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPeminjamActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_editPeminjamActionPerformed

	private void koleksiMajalahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_koleksiMajalahActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_koleksiMajalahActionPerformed

	/**
	 * Mengganti formulir ke registrasi peminjam dengan container {@link CardLayout} (formContainer).
	 */
	private void tambahPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPeminjamActionPerformed
		formCards.show(formContainer, "card1");
	}//GEN-LAST:event_tambahPeminjamActionPerformed

	/**
	 * Mengganti formulir ke registrasi koleksi dengan container {@link CardLayout} (formContainer).
	 */
	private void tambahKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahKoleksiActionPerformed
		formCards.show(formContainer, "card2");
	}//GEN-LAST:event_tambahKoleksiActionPerformed

	/**
	 * Membuang {@link App} ini jika {@link App#homePage} sudah diatur. Membuka frame {@link App#homePage}.
	 */
	private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
		if (homePage != null) {
			this.dispose();
			homePage.setVisible(true);
		} else {
			System.err.println("Home page tidak di inisialisasi.");
			// belum ada
		}
	}//GEN-LAST:event_logoutActionPerformed

	/* Getters setters */

	public List<Peminjam> getListCustomer() {
		return dataPerpus.getListPeminjam();
	}

	protected void setListCustomer(List<Peminjam> listPeminjam) {
		this.dataPerpus.setListPeminjam(listPeminjam);
	}

	/* Other functions */

	/**
	 * Metode penjalan kelas.
	 *
	 * @param args the command line arguments
	 */
	public static void main(String[] args) {
		try {
			/* Mengatur look and feels tampilan jendela menjadi Nimbus */
			javax.swing.UIManager.setLookAndFeel(new javax.swing.plaf.nimbus.NimbusLookAndFeel());
			/* Mengantrikan aplikasi ke event queue */
			java.awt.EventQueue.invokeLater(() -> new App().setVisible(true));
		} catch (UnsupportedLookAndFeelException ex) {          // catch error saat look and feel tidak ditemukan
			java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_regKoleksi;
    private javax.swing.JButton b_regPeminjam;
    private javax.swing.JMenuItem editKoleksi;
    private javax.swing.JMenuItem editPeminjam;
    private javax.swing.JPanel formContainer;
    private javax.swing.ButtonGroup inp_regTipeKoleksi;
    private javax.swing.JMenuItem koleksiBuku;
    private javax.swing.JMenuItem koleksiDisk;
    private javax.swing.JMenuItem koleksiMajalah;
    private javax.swing.JLabel l_logoSadhar;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenuBar menuBarMain;
    private javax.swing.JMenu menuBar_edit;
    private javax.swing.JMenu menuBar_informasi;
    private javax.swing.JMenu menuBar_keluar;
    private javax.swing.JMenu menuBar_koleksi;
    private javax.swing.JMenu menuBar_tambah;
    private javax.swing.JMenu menuBar_transaksi;
    private javax.swing.JPanel menuContainer;
    private javax.swing.JLabel menuTitle;
    private javax.swing.JMenuItem tambahKoleksi;
    private javax.swing.JMenuItem tambahPeminjam;
    private javax.swing.JMenuItem transaksiKembali;
    private javax.swing.JMenuItem transaksiPinjam;
    // End of variables declaration//GEN-END:variables
}
