/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import javax.swing.*;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.util.Enumeration;
import java.util.InputMismatchException;
import java.util.Objects;
import java.util.regex.Pattern;

/**
 *
 * @author narwa
 */
public class FormRegistrasiKoleksi extends javax.swing.JPanel {

    private final Color I_RED = new Color(0xFF5959);
    private final JFrame parent;

    /**
     * Creates new form FormRegistrasiKoleksi
     */
    public FormRegistrasiKoleksi(JFrame parent) {
        initComponents();
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inp_regTipeKoleksi = new javax.swing.ButtonGroup();
        registKoleksiTitle = new javax.swing.JLabel();
        l_judulKoleksi = new javax.swing.JLabel();
        i_judulKoleksi = new java.awt.TextField();
        l_penerbit = new javax.swing.JLabel();
        i_penerbit = new java.awt.TextField();
        l_judulBuku4 = new javax.swing.JLabel();
        i_jenisBuku = new javax.swing.JRadioButton();
        i_jenisMajalah = new javax.swing.JRadioButton();
        i_jenisDisk = new javax.swing.JRadioButton();
        l_isbnIssn = new javax.swing.JLabel();
        i_isbnIssn = new java.awt.TextField();
        l_jmlHalaman = new javax.swing.JLabel();
        i_jmlHalaman = new javax.swing.JSpinner();
        l_volume = new javax.swing.JLabel();
        i_volume = new javax.swing.JSpinner();
        l_seri = new javax.swing.JLabel();
        i_seri = new javax.swing.JSpinner();
        l_format = new javax.swing.JLabel();
        i_format = new javax.swing.JComboBox<>();
        b_simpanRegKoleksi = new javax.swing.JButton();
        b_kosongkanRegKoleksi = new javax.swing.JButton();
        l_simpanKoleksiEmptyIndicator = new javax.swing.JLabel();
        i_noIdKoleksi = new java.awt.TextField();
        l_noIdKoleksi = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(729, 517));

        registKoleksiTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registKoleksiTitle.setText("Registrasi Data Koleksi");

        l_judulKoleksi.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_judulKoleksi.setText("Judul / Title");
        l_judulKoleksi.setMaximumSize(new java.awt.Dimension(150, 25));
        l_judulKoleksi.setMinimumSize(new java.awt.Dimension(150, 25));

        i_judulKoleksi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_judulKoleksi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                i_judulKoleksiFocusLost(evt);
            }
        });
        i_judulKoleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_judulKoleksiActionPerformed(evt);
            }
        });

        l_penerbit.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_penerbit.setText("Penerbit");
        l_penerbit.setMaximumSize(new java.awt.Dimension(150, 25));
        l_penerbit.setMinimumSize(new java.awt.Dimension(150, 25));

        i_penerbit.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_penerbit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                i_penerbitFocusLost(evt);
            }
        });
        i_penerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_penerbitActionPerformed(evt);
            }
        });

        l_judulBuku4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_judulBuku4.setText("Tipe Koleksi");
        l_judulBuku4.setMaximumSize(new java.awt.Dimension(150, 25));
        l_judulBuku4.setMinimumSize(new java.awt.Dimension(150, 25));

        inp_regTipeKoleksi.add(i_jenisBuku);
        i_jenisBuku.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        i_jenisBuku.setSelected(true);
        i_jenisBuku.setText("Buku");
        i_jenisBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_jenisBukuActionPerformed(evt);
            }
        });

        inp_regTipeKoleksi.add(i_jenisMajalah);
        i_jenisMajalah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        i_jenisMajalah.setText("Majalah");
        i_jenisMajalah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_jenisMajalahActionPerformed(evt);
            }
        });

        inp_regTipeKoleksi.add(i_jenisDisk);
        i_jenisDisk.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        i_jenisDisk.setText("Disk");
        i_jenisDisk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_jenisDiskActionPerformed(evt);
            }
        });

        l_isbnIssn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_isbnIssn.setText("ISBN / ISSN");
        l_isbnIssn.setMaximumSize(new java.awt.Dimension(150, 25));
        l_isbnIssn.setMinimumSize(new java.awt.Dimension(150, 25));

        i_isbnIssn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_isbnIssn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                i_isbnIssnFocusLost(evt);
            }
        });
        i_isbnIssn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_isbnIssnActionPerformed(evt);
            }
        });

        l_jmlHalaman.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_jmlHalaman.setText("Jml. Halaman");
        l_jmlHalaman.setMaximumSize(new java.awt.Dimension(150, 25));
        l_jmlHalaman.setMinimumSize(new java.awt.Dimension(150, 25));

        i_jmlHalaman.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        i_jmlHalaman.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        l_volume.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_volume.setText("Volume");
        l_volume.setEnabled(false);
        l_volume.setMaximumSize(new java.awt.Dimension(150, 25));
        l_volume.setMinimumSize(new java.awt.Dimension(150, 25));

        i_volume.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        i_volume.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        i_volume.setEnabled(false);

        l_seri.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_seri.setText("Seri");
        l_seri.setEnabled(false);
        l_seri.setMaximumSize(new java.awt.Dimension(150, 25));
        l_seri.setMinimumSize(new java.awt.Dimension(150, 25));

        i_seri.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        i_seri.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        i_seri.setEnabled(false);

        l_format.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_format.setText("Format");
        l_format.setEnabled(false);
        l_format.setMaximumSize(new java.awt.Dimension(150, 25));
        l_format.setMinimumSize(new java.awt.Dimension(150, 25));

        i_format.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Audio", "Video", "Document" }));
        i_format.setEnabled(false);
        i_format.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_formatActionPerformed(evt);
            }
        });

        b_simpanRegKoleksi.setBackground(new java.awt.Color(51, 204, 0));
        b_simpanRegKoleksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_simpanRegKoleksi.setForeground(new java.awt.Color(255, 255, 255));
        b_simpanRegKoleksi.setText("Simpan");
        b_simpanRegKoleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_simpanRegKoleksiActionPerformed(evt);
            }
        });

        b_kosongkanRegKoleksi.setBackground(new java.awt.Color(255, 102, 102));
        b_kosongkanRegKoleksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_kosongkanRegKoleksi.setForeground(new java.awt.Color(255, 255, 255));
        b_kosongkanRegKoleksi.setText("Kosongkan");
        b_kosongkanRegKoleksi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b_kosongkanRegKoleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_kosongkanRegKoleksiActionPerformed(evt);
            }
        });

        l_simpanKoleksiEmptyIndicator.setBackground(new java.awt.Color(153, 153, 153));
        l_simpanKoleksiEmptyIndicator.setForeground(new java.awt.Color(255, 51, 51));
        l_simpanKoleksiEmptyIndicator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_simpanKoleksiEmptyIndicator.setText("Terdapat data yang masih kosong atau tidak benar!");
        l_simpanKoleksiEmptyIndicator.setVisible(false);

        i_noIdKoleksi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_noIdKoleksi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                i_noIdKoleksiFocusLost(evt);
            }
        });
        i_noIdKoleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_noIdKoleksiActionPerformed(evt);
            }
        });

        l_noIdKoleksi.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_noIdKoleksi.setText("Id. Koleksi (6 digit)");
        l_noIdKoleksi.setToolTipText("Kode: B / Buku; M / Majalah; D / Disk");
        l_noIdKoleksi.setMaximumSize(new java.awt.Dimension(150, 25));
        l_noIdKoleksi.setMinimumSize(new java.awt.Dimension(150, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(l_simpanKoleksiEmptyIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_kosongkanRegKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b_simpanRegKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registKoleksiTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(l_penerbit, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(l_isbnIssn, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(l_judulBuku4, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(l_jmlHalaman, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(l_volume, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(l_judulKoleksi, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(l_format, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(l_seri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(l_noIdKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(i_judulKoleksi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(i_jenisBuku)
                                    .addComponent(i_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(i_jenisMajalah)
                                    .addComponent(i_jenisDisk)
                                    .addComponent(i_isbnIssn, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(i_jmlHalaman, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(i_volume, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(i_noIdKoleksi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(i_format, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(i_seri, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registKoleksiTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(i_judulKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_judulKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(i_isbnIssn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_isbnIssn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(i_jenisBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_judulBuku4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(i_jenisMajalah, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(i_jenisDisk, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(i_jmlHalaman, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(l_jmlHalaman, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(i_volume, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(l_volume, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_seri, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i_seri, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_format, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i_format, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_noIdKoleksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i_noIdKoleksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_simpanRegKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_kosongkanRegKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_simpanKoleksiEmptyIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        l_noIdKoleksi.getAccessibleContext().setAccessibleDescription("Identifier Koleksi");
    }// </editor-fold>//GEN-END:initComponents

    private void i_judulKoleksiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_i_judulKoleksiFocusLost
        String text = i_judulKoleksi.getText().trim();
/*        if (!Checker.isAlphabetSpace(text, 3)) {
            i_judulKoleksi.setBackground(I_RED);
        } else {
            i_judulKoleksi.setBackground(Color.WHITE);
        }*/
        // TODO: [REMOVE LATER] COUNT THIS AS TRY-CATCH: 1
        try {
            if (!Checker.isAlphabetSpace(text, 3)) {
                throw new InputMismatchException();
            }
            i_judulKoleksi.setBackground(Color.WHITE);
        } catch (InputMismatchException ex) {
            i_judulKoleksi.setBackground(I_RED);
        }
    }//GEN-LAST:event_i_judulKoleksiFocusLost

    private void i_judulKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_judulKoleksiActionPerformed

    }//GEN-LAST:event_i_judulKoleksiActionPerformed

    private void i_penerbitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_i_penerbitFocusLost
        String text = i_penerbit.getText().trim();
/*        if (!Checker.isAlphabetSpace(text, 3)) {
            i_penerbit.setBackground(I_RED);
        } else {
            i_penerbit.setBackground(Color.WHITE);
        }*/
        // TODO: [REMOVE LATER] COUNT THIS AS TRY-CATCH: 2
        try {
            if (!Checker.isAlphabetSpace(text, 3)) {
                throw new InputMismatchException();
            }
            i_penerbit.setBackground(Color.WHITE);
        } catch (InputMismatchException ex) {
            i_penerbit.setBackground(I_RED);
        }
    }//GEN-LAST:event_i_penerbitFocusLost

    private void i_penerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_penerbitActionPerformed

    }//GEN-LAST:event_i_penerbitActionPerformed

    private void i_jenisBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_jenisBukuActionPerformed
        setFalseAllTipeKoleksi();                               // mematikan semua fields spesifik

        /* Menyalakan label dan input yang relevan dengan tipe koleksinya. l: Label, i: Input.*/
        l_jmlHalaman.setEnabled(true);
        i_jmlHalaman.setEnabled(true);
    }//GEN-LAST:event_i_jenisBukuActionPerformed

    private void i_jenisMajalahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_jenisMajalahActionPerformed
        setFalseAllTipeKoleksi();                               // mematikan semua fields spesifik

        /* Menyalakan label dan input yang relevan dengan tipe koleksinya. l: Label, i: Input.*/
        l_volume.setEnabled(true);
        i_volume.setEnabled(true);
        l_seri.setEnabled(true);
        i_seri.setEnabled(true);
    }//GEN-LAST:event_i_jenisMajalahActionPerformed

    private void i_jenisDiskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_jenisDiskActionPerformed
        setFalseAllTipeKoleksi();                               // mematikan semua fields spesifik

        /* Menyalakan label dan input yang relevan dengan tipe koleksinya. l: Label, i: Input.*/
        l_format.setEnabled(true);
        i_format.setEnabled(true);
    }//GEN-LAST:event_i_jenisDiskActionPerformed

    private void i_isbnIssnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_i_isbnIssnFocusLost
/*        if (!Checker.isNomorSpaceHyphen(i_isbnIssn.getText().trim())) {
            i_isbnIssn.setBackground(I_RED);
        } else {
            i_isbnIssn.setBackground(Color.WHITE);
        }*/
        // TODO: [REMOVE LATER] COUNT THIS AS TRY-CATCH: 3
        try {
            if (!Checker.isNomor(i_isbnIssn.getText().trim().replaceAll("[\\s-]+", ""), 13)) {
                throw new InputMismatchException();
            }
            i_isbnIssn.setBackground(Color.WHITE);
        } catch (InputMismatchException ex) {
            i_isbnIssn.setBackground(I_RED);
        }
    }//GEN-LAST:event_i_isbnIssnFocusLost

    private void i_isbnIssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_isbnIssnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_isbnIssnActionPerformed

    private void i_formatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_formatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_formatActionPerformed

    private void b_simpanRegKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_simpanRegKoleksiActionPerformed
        /* Variabel-variabel penyimpan data */
        String judul = i_judulKoleksi.getText().trim();
        String penerbit = i_penerbit.getText().trim();
        String isbnIssn = i_isbnIssn.getText().trim().replaceAll("[\\s-]+", "");

        String tipeKoleksi = "";
        /* Melakukan iterasi setiap button pada button group, mencari button yang dipilih. */
        for (Enumeration<AbstractButton> bg = inp_regTipeKoleksi.getElements(); bg.hasMoreElements(); ) {
            AbstractButton b = bg.nextElement();

            if (b.isSelected()) {
                tipeKoleksi = b.getText();
                break;
            }
        }

        /* Variabel-variabel penyimpan data (2) */
        int jmlHalaman = (int) i_jmlHalaman.getValue();
        int volume = (int) i_volume.getValue();
        int seri = (int) i_seri.getValue();
        String format = (String) i_format.getSelectedItem();
        String noIdKoleksi = i_noIdKoleksi.getText().trim().replaceAll(" ", "");

        FocusEvent eventPlaceholder = new FocusEvent(this, FocusEvent.FOCUS_LOST);
        /* mengecek apakah terdapat field yang kosong setelah ditrim */
        for (TextField field : new TextField[]{i_judulKoleksi, i_penerbit, i_isbnIssn}) {
            if (Checker.stringIsEmpty(field.getText().trim())) {
                l_simpanKoleksiEmptyIndicator.setVisible(true);
                field.getFocusListeners()[0].focusLost(eventPlaceholder);
                JOptionPane.showMessageDialog(
                    this.parent,
                    "Terdapat field input yang masih kosong/salah! (Highlight merah)",
                    "Warning",
                    JOptionPane.INFORMATION_MESSAGE
                );
                return;
            }
        }
        /* mengecek apakah format isbn sudah valid*/
        if (!Checker.isNomor(isbnIssn, 13)) {
            l_simpanKoleksiEmptyIndicator.setVisible(true);
            JOptionPane.showMessageDialog(
                this.parent,
                "Field ISBN belum sesuai! Harap masukkan 13 digit nomor ISBN!",
                "Warning",
                JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }
        l_simpanKoleksiEmptyIndicator.setVisible(false);

        // TODO: [REMOVE LATER] COUNT THIS AS TRY-CATCH: 4
        try {
            if (!noIdKoleksi.matches(String.format("^[%s]+[0-9]{5}$",
            (tipeKoleksi.equals("Buku") ? "B" : (tipeKoleksi.equals("Majalah")) ? "M" : "D")))) {
                throw new InputMismatchException("Nomor id koleksi masih belum sesuai!");
            }
        } catch (InputMismatchException ex) {
            JOptionPane.showMessageDialog(
                this.parent,
                ex.getMessage(),
                "Warning",
                JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }

        final String finalTipeKoleksi = tipeKoleksi;
        switch (tipeKoleksi) {
            case "Buku" -> EventQueue.invokeLater(
                () -> new RegistrasiKoleksiBerhasil(parent, true)
                    .isiField(finalTipeKoleksi, judul, penerbit, isbnIssn, jmlHalaman, noIdKoleksi)
                    .setVisible(true)
            );
            case "Majalah" -> EventQueue.invokeLater(
                () -> new RegistrasiKoleksiBerhasil(parent, true)
                    .isiField(finalTipeKoleksi, judul, penerbit, isbnIssn, volume, seri, noIdKoleksi)
                    .setVisible(true)
            );
            default -> EventQueue.invokeLater(
                () -> new RegistrasiKoleksiBerhasil(parent, true)
                    .isiField(finalTipeKoleksi, judul, penerbit, isbnIssn, format, noIdKoleksi)
                    .setVisible(true)
            );
        }
        kosongkanRegKoleksi();

        /* Print data */
        System.out.printf("""
            Saved koleksi baru: {
                    judul: "%s",
                    penerbit: "%s",
                    isbnIssn: "%s",
                    tipeKoleksi: "%s",
                    jmlHalaman: %1d,
                    volume: %1d,
                    seri: %1d,
                    format: "%s"
            }
            """,
            judul, penerbit, isbnIssn, tipeKoleksi, jmlHalaman, volume, seri, format
        );
    }//GEN-LAST:event_b_simpanRegKoleksiActionPerformed

    private void b_kosongkanRegKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_kosongkanRegKoleksiActionPerformed
        kosongkanRegKoleksi();                              // panggil metode yang mengosongkan reg. peminjam

        l_simpanKoleksiEmptyIndicator.setVisible(false);    // mematikan indikator field masih kosong
    }//GEN-LAST:event_b_kosongkanRegKoleksiActionPerformed

    private void i_noIdKoleksiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_i_noIdKoleksiFocusLost
        String tipeKoleksi = "";
        /* Melakukan iterasi setiap button pada button group, mencari button yang dipilih. */
        for (Enumeration<AbstractButton> bg = inp_regTipeKoleksi.getElements(); bg.hasMoreElements(); ) {
            AbstractButton b = bg.nextElement();

            if (b.isSelected()) {
                tipeKoleksi = b.getText();
                break;
            }
        }
        String text = i_noIdKoleksi.getText().trim();
        if (!text.matches(String.format("^[%s]+[0-9]{5}$",
            (tipeKoleksi.equals("Buku") ? "B" : (tipeKoleksi.equals("Majalah")) ? "M" : "D")))) {
            i_noIdKoleksi.setBackground(I_RED);
        } else {
            i_noIdKoleksi.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_i_noIdKoleksiFocusLost

    private void i_noIdKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_noIdKoleksiActionPerformed
        // TODO: Nothing there
    }//GEN-LAST:event_i_noIdKoleksiActionPerformed

    /**
     * Menyetel seluruh fields spesial dalam formulir registrasi koleksi ke mati (disabled).
     */
    private void setFalseAllTipeKoleksi() {
        l_jmlHalaman.setEnabled(false);
        i_jmlHalaman.setEnabled(false);
        l_volume.setEnabled(false);
        i_volume.setEnabled(false);
        l_seri.setEnabled(false);
        i_seri.setEnabled(false);
        l_format.setEnabled(false);
        i_format.setEnabled(false);
    }

    /**
     * Mengosongkan/mengatur seluruh field registrasi koleksi dengan nilai awal.
     */
    private void kosongkanRegKoleksi() {
        i_judulKoleksi.setText("");
        i_penerbit.setText("");
        i_isbnIssn.setText("");

        /* Memilih pilihan "Buku" dan mematikan kolom input spesifik lain kecuali jumlah halaman */
        inp_regTipeKoleksi.setSelected(i_jenisBuku.getModel(), true);
        setFalseAllTipeKoleksi();
        l_jmlHalaman.setEnabled(true);
        i_jmlHalaman.setEnabled(true);

        i_jmlHalaman.setValue(1);
        i_volume.setValue(1);
        i_seri.setValue(1);
        i_format.setSelectedIndex(0);
        i_noIdKoleksi.setText("");

        /* Melakukan reset warna background tiap field menjadi putih */
        for (TextField c : new TextField[] {i_judulKoleksi, i_penerbit, i_isbnIssn, i_noIdKoleksi}) {
            c.setBackground(Color.WHITE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_kosongkanRegKoleksi;
    private javax.swing.JButton b_simpanRegKoleksi;
    private javax.swing.JComboBox<String> i_format;
    private java.awt.TextField i_isbnIssn;
    private javax.swing.JRadioButton i_jenisBuku;
    private javax.swing.JRadioButton i_jenisDisk;
    private javax.swing.JRadioButton i_jenisMajalah;
    private javax.swing.JSpinner i_jmlHalaman;
    private java.awt.TextField i_judulKoleksi;
    private java.awt.TextField i_noIdKoleksi;
    private java.awt.TextField i_penerbit;
    private javax.swing.JSpinner i_seri;
    private javax.swing.JSpinner i_volume;
    private javax.swing.ButtonGroup inp_regTipeKoleksi;
    private javax.swing.JLabel l_format;
    private javax.swing.JLabel l_isbnIssn;
    private javax.swing.JLabel l_jmlHalaman;
    private javax.swing.JLabel l_judulBuku4;
    private javax.swing.JLabel l_judulKoleksi;
    private javax.swing.JLabel l_noIdKoleksi;
    private javax.swing.JLabel l_penerbit;
    private javax.swing.JLabel l_seri;
    private javax.swing.JLabel l_simpanKoleksiEmptyIndicator;
    private javax.swing.JLabel l_volume;
    private javax.swing.JLabel registKoleksiTitle;
    // End of variables declaration//GEN-END:variables
}
