/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author narwa
 */
public class FormTransaksi extends javax.swing.JFrame {

    /**
     * Creates new form FormTransaksi
     */
    public FormTransaksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Koleksi = new javax.swing.JPanel();
        b_cekKoleksi = new javax.swing.JButton();
        i_judulKoleksi = new java.awt.TextField();
        i_kodeKoleksi = new java.awt.TextField();
        l_pencarianKoleksi = new javax.swing.JLabel();
        i_judulKoleksi1 = new java.awt.TextField();
        l_nama = new javax.swing.JLabel();
        i_judulKoleksi2 = new java.awt.TextField();
        l_nama1 = new javax.swing.JLabel();
        l_nama2 = new javax.swing.JLabel();
        i_judulKoleksi3 = new java.awt.TextField();
        i_judulKoleksi4 = new java.awt.TextField();
        l_nama3 = new javax.swing.JLabel();
        panel_PeminjamDeadline = new javax.swing.JPanel();
        l_pencarianPeminjam = new javax.swing.JLabel();
        b_cekPeminjam = new javax.swing.JButton();
        i_noIdentitasPeminjam = new java.awt.TextField();
        i_kodePeminjam = new java.awt.TextField();
        l_namaPeminjam = new javax.swing.JLabel();
        i_namaPeminjam = new java.awt.TextField();
        i_maksPinjam = new java.awt.TextField();
        l_namaPeminjam1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        l_namaPeminjam2 = new javax.swing.JLabel();
        i_namaPeminjam1 = new java.awt.TextField();
        b_kosongkanTransaksi = new javax.swing.JButton();
        b_konfirmasiTransaksi = new javax.swing.JButton();
        b_kembali = new javax.swing.JButton();
        panel_keranjangTable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        panel_transaksiTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Input Transaksi Peminjaman");
        setMaximumSize(new java.awt.Dimension(960, 540));
        setMinimumSize(new java.awt.Dimension(960, 540));
        setResizable(false);

        panel_Koleksi.setBackground(new java.awt.Color(153, 204, 255));
        panel_Koleksi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_Koleksi.setPreferredSize(new java.awt.Dimension(480, 270));

        b_cekKoleksi.setText("Cari");
        b_cekKoleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cekKoleksiActionPerformed(evt);
            }
        });

        i_judulKoleksi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_judulKoleksi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                i_judulKoleksiFocusLost(evt);
            }
        });
        i_judulKoleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_judulKoleksiActionPerformed(evt);
            }
        });

        i_kodeKoleksi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_kodeKoleksi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                i_kodeKoleksiFocusLost(evt);
            }
        });
        i_kodeKoleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_kodeKoleksiActionPerformed(evt);
            }
        });

        l_pencarianKoleksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l_pencarianKoleksi.setForeground(new java.awt.Color(0, 0, 0));
        l_pencarianKoleksi.setText("Pencarian Koleksi");

        i_judulKoleksi1.setEnabled(false);
        i_judulKoleksi1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_judulKoleksi1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                i_judulKoleksi1FocusLost(evt);
            }
        });
        i_judulKoleksi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_judulKoleksi1ActionPerformed(evt);
            }
        });

        l_nama.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        l_nama.setForeground(new java.awt.Color(51, 51, 51));
        l_nama.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        l_nama.setText("Judul");
        l_nama.setToolTipText("");
        l_nama.setMaximumSize(new java.awt.Dimension(150, 25));
        l_nama.setMinimumSize(new java.awt.Dimension(150, 25));

        i_judulKoleksi2.setEnabled(false);
        i_judulKoleksi2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_judulKoleksi2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                i_judulKoleksi2FocusLost(evt);
            }
        });
        i_judulKoleksi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_judulKoleksi2ActionPerformed(evt);
            }
        });

        l_nama1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        l_nama1.setForeground(new java.awt.Color(51, 51, 51));
        l_nama1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        l_nama1.setText("Penerbit");
        l_nama1.setToolTipText("");
        l_nama1.setMaximumSize(new java.awt.Dimension(150, 25));
        l_nama1.setMinimumSize(new java.awt.Dimension(150, 25));

        l_nama2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        l_nama2.setForeground(new java.awt.Color(51, 51, 51));
        l_nama2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        l_nama2.setText("ISSN/ISBN");
        l_nama2.setToolTipText("");
        l_nama2.setMaximumSize(new java.awt.Dimension(150, 25));
        l_nama2.setMinimumSize(new java.awt.Dimension(150, 25));

        i_judulKoleksi3.setEnabled(false);
        i_judulKoleksi3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_judulKoleksi3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                i_judulKoleksi3FocusLost(evt);
            }
        });
        i_judulKoleksi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_judulKoleksi3ActionPerformed(evt);
            }
        });

        i_judulKoleksi4.setEnabled(false);
        i_judulKoleksi4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_judulKoleksi4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                i_judulKoleksi4FocusLost(evt);
            }
        });
        i_judulKoleksi4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_judulKoleksi4ActionPerformed(evt);
            }
        });

        l_nama3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        l_nama3.setForeground(new java.awt.Color(51, 51, 51));
        l_nama3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        l_nama3.setText("Tipe Koleksi");
        l_nama3.setToolTipText("");
        l_nama3.setMaximumSize(new java.awt.Dimension(150, 25));
        l_nama3.setMinimumSize(new java.awt.Dimension(150, 25));

        javax.swing.GroupLayout panel_KoleksiLayout = new javax.swing.GroupLayout(panel_Koleksi);
        panel_Koleksi.setLayout(panel_KoleksiLayout);
        panel_KoleksiLayout.setHorizontalGroup(
            panel_KoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_KoleksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_KoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_KoleksiLayout.createSequentialGroup()
                        .addComponent(l_pencarianKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 230, Short.MAX_VALUE))
                    .addGroup(panel_KoleksiLayout.createSequentialGroup()
                        .addComponent(i_kodeKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(i_judulKoleksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_cekKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_KoleksiLayout.createSequentialGroup()
                        .addGroup(panel_KoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_KoleksiLayout.createSequentialGroup()
                                .addComponent(l_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(i_judulKoleksi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panel_KoleksiLayout.createSequentialGroup()
                                .addComponent(l_nama1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(i_judulKoleksi2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panel_KoleksiLayout.createSequentialGroup()
                                .addComponent(l_nama2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(i_judulKoleksi3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panel_KoleksiLayout.createSequentialGroup()
                                .addComponent(l_nama3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(i_judulKoleksi4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(80, 80, 80)))
                .addContainerGap())
        );
        panel_KoleksiLayout.setVerticalGroup(
            panel_KoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_KoleksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_pencarianKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_KoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_cekKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_KoleksiLayout.createSequentialGroup()
                        .addGroup(panel_KoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(i_judulKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(i_kodeKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_KoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(i_judulKoleksi1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_KoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_nama1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(i_judulKoleksi2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_KoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_nama2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(i_judulKoleksi3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_KoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_nama3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(i_judulKoleksi4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        panel_PeminjamDeadline.setBackground(new java.awt.Color(153, 204, 255));
        panel_PeminjamDeadline.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_PeminjamDeadline.setPreferredSize(new java.awt.Dimension(480, 270));

        l_pencarianPeminjam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l_pencarianPeminjam.setForeground(new java.awt.Color(0, 0, 0));
        l_pencarianPeminjam.setText("Pencarian Peminjam");

        b_cekPeminjam.setText("Cari");
        b_cekPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cekPeminjamActionPerformed(evt);
            }
        });

        i_noIdentitasPeminjam.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_noIdentitasPeminjam.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                i_noIdentitasPeminjamFocusLost(evt);
            }
        });
        i_noIdentitasPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_noIdentitasPeminjamActionPerformed(evt);
            }
        });

        i_kodePeminjam.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_kodePeminjam.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                i_kodePeminjamFocusLost(evt);
            }
        });
        i_kodePeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_kodePeminjamActionPerformed(evt);
            }
        });

        l_namaPeminjam.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        l_namaPeminjam.setForeground(new java.awt.Color(51, 51, 51));
        l_namaPeminjam.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        l_namaPeminjam.setText("Nama");
        l_namaPeminjam.setToolTipText("");
        l_namaPeminjam.setMaximumSize(new java.awt.Dimension(150, 25));
        l_namaPeminjam.setMinimumSize(new java.awt.Dimension(150, 25));

        i_namaPeminjam.setEnabled(false);
        i_namaPeminjam.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_namaPeminjam.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                i_namaPeminjamFocusLost(evt);
            }
        });
        i_namaPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_namaPeminjamActionPerformed(evt);
            }
        });

        i_maksPinjam.setEnabled(false);
        i_maksPinjam.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_maksPinjam.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                i_maksPinjamFocusLost(evt);
            }
        });
        i_maksPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_maksPinjamActionPerformed(evt);
            }
        });

        l_namaPeminjam1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        l_namaPeminjam1.setForeground(new java.awt.Color(51, 51, 51));
        l_namaPeminjam1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        l_namaPeminjam1.setText("Lama Pinjam");
        l_namaPeminjam1.setToolTipText("");
        l_namaPeminjam1.setMaximumSize(new java.awt.Dimension(150, 25));
        l_namaPeminjam1.setMinimumSize(new java.awt.Dimension(150, 25));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Minggu", "2 Minggu", "3 Minggu", "4 Minggu" }));

        l_namaPeminjam2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        l_namaPeminjam2.setForeground(new java.awt.Color(51, 51, 51));
        l_namaPeminjam2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        l_namaPeminjam2.setText("Dari");
        l_namaPeminjam2.setToolTipText("");
        l_namaPeminjam2.setMaximumSize(new java.awt.Dimension(150, 25));
        l_namaPeminjam2.setMinimumSize(new java.awt.Dimension(150, 25));

        i_namaPeminjam1.setEnabled(false);
        i_namaPeminjam1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_namaPeminjam1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                i_namaPeminjam1FocusLost(evt);
            }
        });
        i_namaPeminjam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_namaPeminjam1ActionPerformed(evt);
            }
        });

        b_kosongkanTransaksi.setBackground(new java.awt.Color(255, 102, 102));
        b_kosongkanTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_kosongkanTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        b_kosongkanTransaksi.setText("Kosongkan");
        b_kosongkanTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b_kosongkanTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_kosongkanTransaksiActionPerformed(evt);
            }
        });

        b_konfirmasiTransaksi.setBackground(new java.awt.Color(51, 204, 0));
        b_konfirmasiTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_konfirmasiTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        b_konfirmasiTransaksi.setText("Simpan");
        b_konfirmasiTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_konfirmasiTransaksiActionPerformed(evt);
            }
        });

        b_kembali.setBackground(new java.awt.Color(255, 204, 153));
        b_kembali.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_kembali.setForeground(new java.awt.Color(255, 255, 255));
        b_kembali.setText("Kembali");
        b_kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_kembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_PeminjamDeadlineLayout = new javax.swing.GroupLayout(panel_PeminjamDeadline);
        panel_PeminjamDeadline.setLayout(panel_PeminjamDeadlineLayout);
        panel_PeminjamDeadlineLayout.setHorizontalGroup(
            panel_PeminjamDeadlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_PeminjamDeadlineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_PeminjamDeadlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_PeminjamDeadlineLayout.createSequentialGroup()
                        .addGroup(panel_PeminjamDeadlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_PeminjamDeadlineLayout.createSequentialGroup()
                                .addComponent(i_kodePeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(i_noIdentitasPeminjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panel_PeminjamDeadlineLayout.createSequentialGroup()
                                .addComponent(l_namaPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(i_namaPeminjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_PeminjamDeadlineLayout.createSequentialGroup()
                                .addComponent(l_namaPeminjam1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(l_namaPeminjam2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(i_namaPeminjam1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_PeminjamDeadlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_cekPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(i_maksPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_PeminjamDeadlineLayout.createSequentialGroup()
                        .addComponent(l_pencarianPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_PeminjamDeadlineLayout.createSequentialGroup()
                        .addComponent(b_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_kosongkanTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b_konfirmasiTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel_PeminjamDeadlineLayout.setVerticalGroup(
            panel_PeminjamDeadlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_PeminjamDeadlineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_pencarianPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_PeminjamDeadlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_PeminjamDeadlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(i_noIdentitasPeminjam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(i_kodePeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(b_cekPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_PeminjamDeadlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(i_maksPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i_namaPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_namaPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_PeminjamDeadlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(i_namaPeminjam1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_PeminjamDeadlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(l_namaPeminjam1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(l_namaPeminjam2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(panel_PeminjamDeadlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_konfirmasiTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_kosongkanTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panel_keranjangTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_keranjangTable.setPreferredSize(new java.awt.Dimension(480, 270));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "title", "tipe", "included"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tabel Keranjang");

        javax.swing.GroupLayout panel_keranjangTableLayout = new javax.swing.GroupLayout(panel_keranjangTable);
        panel_keranjangTable.setLayout(panel_keranjangTableLayout);
        panel_keranjangTableLayout.setHorizontalGroup(
            panel_keranjangTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_keranjangTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_keranjangTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panel_keranjangTableLayout.setVerticalGroup(
            panel_keranjangTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_keranjangTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel_transaksiTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_transaksiTable.setPreferredSize(new java.awt.Dimension(480, 270));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "customer id", "at", "end", "amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tabel Transaksi");

        javax.swing.GroupLayout panel_transaksiTableLayout = new javax.swing.GroupLayout(panel_transaksiTable);
        panel_transaksiTable.setLayout(panel_transaksiTableLayout);
        panel_transaksiTableLayout.setHorizontalGroup(
            panel_transaksiTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_transaksiTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_transaksiTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panel_transaksiTableLayout.setVerticalGroup(
            panel_transaksiTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_transaksiTableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_Koleksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_PeminjamDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_transaksiTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_keranjangTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel_Koleksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(panel_PeminjamDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel_keranjangTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(panel_transaksiTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        setSize(new java.awt.Dimension(974, 577));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_cekKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cekKoleksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_cekKoleksiActionPerformed

    private void i_judulKoleksiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_i_judulKoleksiFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_i_judulKoleksiFocusLost

    private void i_judulKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_judulKoleksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_judulKoleksiActionPerformed

    private void i_kodeKoleksiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_i_kodeKoleksiFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_i_kodeKoleksiFocusLost

    private void i_kodeKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_kodeKoleksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_kodeKoleksiActionPerformed

    private void b_cekPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cekPeminjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_cekPeminjamActionPerformed

    private void i_noIdentitasPeminjamFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_i_noIdentitasPeminjamFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_i_noIdentitasPeminjamFocusLost

    private void i_noIdentitasPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_noIdentitasPeminjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_noIdentitasPeminjamActionPerformed

    private void i_kodePeminjamFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_i_kodePeminjamFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_i_kodePeminjamFocusLost

    private void i_kodePeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_kodePeminjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_kodePeminjamActionPerformed

    private void i_judulKoleksi1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_i_judulKoleksi1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_i_judulKoleksi1FocusLost

    private void i_judulKoleksi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_judulKoleksi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_judulKoleksi1ActionPerformed

    private void i_judulKoleksi2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_i_judulKoleksi2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_i_judulKoleksi2FocusLost

    private void i_judulKoleksi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_judulKoleksi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_judulKoleksi2ActionPerformed

    private void i_judulKoleksi3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_i_judulKoleksi3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_i_judulKoleksi3FocusLost

    private void i_judulKoleksi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_judulKoleksi3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_judulKoleksi3ActionPerformed

    private void i_judulKoleksi4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_i_judulKoleksi4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_i_judulKoleksi4FocusLost

    private void i_judulKoleksi4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_judulKoleksi4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_judulKoleksi4ActionPerformed

    private void i_namaPeminjamFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_i_namaPeminjamFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_i_namaPeminjamFocusLost

    private void i_namaPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_namaPeminjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_namaPeminjamActionPerformed

    private void i_maksPinjamFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_i_maksPinjamFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_i_maksPinjamFocusLost

    private void i_maksPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_maksPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_maksPinjamActionPerformed

    private void i_namaPeminjam1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_i_namaPeminjam1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_i_namaPeminjam1FocusLost

    private void i_namaPeminjam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_namaPeminjam1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_namaPeminjam1ActionPerformed

    private void b_kosongkanTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_kosongkanTransaksiActionPerformed

    }//GEN-LAST:event_b_kosongkanTransaksiActionPerformed

    private void b_konfirmasiTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_konfirmasiTransaksiActionPerformed
        /* Variabel-variabel penyimpan data DENGAN regex */

    }//GEN-LAST:event_b_konfirmasiTransaksiActionPerformed

    private void b_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_kembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cekKoleksi;
    private javax.swing.JButton b_cekPeminjam;
    private javax.swing.JButton b_kembali;
    private javax.swing.JButton b_konfirmasiTransaksi;
    private javax.swing.JButton b_kosongkanTransaksi;
    private java.awt.TextField i_judulKoleksi;
    private java.awt.TextField i_judulKoleksi1;
    private java.awt.TextField i_judulKoleksi2;
    private java.awt.TextField i_judulKoleksi3;
    private java.awt.TextField i_judulKoleksi4;
    private java.awt.TextField i_kodeKoleksi;
    private java.awt.TextField i_kodePeminjam;
    private java.awt.TextField i_maksPinjam;
    private java.awt.TextField i_namaPeminjam;
    private java.awt.TextField i_namaPeminjam1;
    private java.awt.TextField i_noIdentitasPeminjam;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel l_nama;
    private javax.swing.JLabel l_nama1;
    private javax.swing.JLabel l_nama2;
    private javax.swing.JLabel l_nama3;
    private javax.swing.JLabel l_namaPeminjam;
    private javax.swing.JLabel l_namaPeminjam1;
    private javax.swing.JLabel l_namaPeminjam2;
    private javax.swing.JLabel l_pencarianKoleksi;
    private javax.swing.JLabel l_pencarianPeminjam;
    private javax.swing.JPanel panel_Koleksi;
    private javax.swing.JPanel panel_PeminjamDeadline;
    private javax.swing.JPanel panel_keranjangTable;
    private javax.swing.JPanel panel_transaksiTable;
    // End of variables declaration//GEN-END:variables
}
