/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbol.gui.app;

import java.awt.*;
import java.util.HashMap;

/**
 *
 * @author narwa
 */
public class App extends javax.swing.JFrame {

    private final CardLayout formCards;
    private HashMap<String, Component> components;
    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        setTitle("Sistem Manajemen Perpustakaan");
        formCards = (CardLayout) formContainer.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inp_regTipeKoleksi = new javax.swing.ButtonGroup();
        menuContainer = new javax.swing.JPanel();
        menuTitle = new javax.swing.JLabel();
        btn_regPeminjam = new javax.swing.JButton();
        btn_regKoleksi = new javax.swing.JButton();
        formContainer = new javax.swing.JPanel();
        registrasiPeminjam = new javax.swing.JPanel();
        regisPeminjamTitle = new javax.swing.JLabel();
        l_nama = new javax.swing.JLabel();
        inpNama = new java.awt.TextField();
        l_Id = new javax.swing.JLabel();
        inpId = new java.awt.TextField();
        inpJenisId = new javax.swing.JComboBox<>();
        l_alamat = new javax.swing.JLabel();
        inpAlamat = new java.awt.TextField();
        l_telp = new javax.swing.JLabel();
        inpTelp = new java.awt.TextField();
        l_maksPinjam = new javax.swing.JLabel();
        inpMaksPinjam = new javax.swing.JSpinner();
        btnSimpanData = new javax.swing.JButton();
        btnKosongkanData = new javax.swing.JButton();
        registrasiKoleksi = new javax.swing.JPanel();
        registKoleksiTitle = new javax.swing.JLabel();
        l_judulBuku = new javax.swing.JLabel();
        inpJudulBuku = new java.awt.TextField();
        l_penerbit = new javax.swing.JLabel();
        inpPenerbit = new java.awt.TextField();
        l_judulBuku4 = new javax.swing.JLabel();
        inpTipeBuku = new javax.swing.JRadioButton();
        inpTipeMajalah = new javax.swing.JRadioButton();
        inpTipeDisk = new javax.swing.JRadioButton();
        l_isbnIssn = new javax.swing.JLabel();
        inpIsbnIssn = new java.awt.TextField();
        l_jmlHalaman = new javax.swing.JLabel();
        inpJmlHalaman = new javax.swing.JSpinner();
        l_volume = new javax.swing.JLabel();
        inpVolume = new javax.swing.JSpinner();
        l_seri = new javax.swing.JLabel();
        inpSeri = new javax.swing.JSpinner();
        l_format = new javax.swing.JLabel();
        inpFormat = new java.awt.TextField();
        btnSimpanBuku = new javax.swing.JButton();
        btlKosongkan = new javax.swing.JButton();
        menuBarMain = new javax.swing.JMenuBar();
        menuBar_info = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(960, 540));

        menuContainer.setBackground(new java.awt.Color(153, 204, 255));

        menuTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuTitle.setForeground(new java.awt.Color(51, 102, 255));
        menuTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTitle.setText("<html>Sistem Manajemen<br/>Perpustakaan</html>");

        btn_regPeminjam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_regPeminjam.setText("Registrasi Peminjam");
        btn_regPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regPeminjamActionPerformed(evt);
            }
        });

        btn_regKoleksi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_regKoleksi.setText("Registrasi Koleksi");
        btn_regKoleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regKoleksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuContainerLayout = new javax.swing.GroupLayout(menuContainer);
        menuContainer.setLayout(menuContainerLayout);
        menuContainerLayout.setHorizontalGroup(
            menuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(btn_regPeminjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_regKoleksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuContainerLayout.setVerticalGroup(
            menuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_regPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_regKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(331, Short.MAX_VALUE))
        );

        formContainer.setBackground(new java.awt.Color(255, 255, 255));
        formContainer.setLayout(new java.awt.CardLayout());

        registrasiPeminjam.setPreferredSize(new java.awt.Dimension(700, 540));

        regisPeminjamTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        regisPeminjamTitle.setText("Registrasi Data Peminjam");

        l_nama.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_nama.setText("Nama Lengkap");

        inpNama.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inpNama.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        inpNama.setName(""); // NOI18N
        inpNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpNamaActionPerformed(evt);
            }
        });

        l_Id.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_Id.setText("Nomor Identitas");

        inpId.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        inpId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpIdActionPerformed(evt);
            }
        });

        inpJenisId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inpJenisId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIM", "NIP", "NIK" }));
        inpJenisId.setToolTipText("Jenis Nomor Identitas");
        inpJenisId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpJenisIdActionPerformed(evt);
            }
        });

        l_alamat.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_alamat.setText("Alamat");

        inpAlamat.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        inpAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpAlamatActionPerformed(evt);
            }
        });

        l_telp.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_telp.setText("Nomor Telepon");

        inpTelp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        inpTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpTelpActionPerformed(evt);
            }
        });

        l_maksPinjam.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_maksPinjam.setText("Maks. Pinjaman");

        inpMaksPinjam.setModel(new javax.swing.SpinnerNumberModel(1, 0, 10, 1));

        btnSimpanData.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSimpanData.setText("Simpan");
        btnSimpanData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanDataActionPerformed(evt);
            }
        });

        btnKosongkanData.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnKosongkanData.setText("Kosongkan");
        btnKosongkanData.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnKosongkanData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKosongkanDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registrasiPeminjamLayout = new javax.swing.GroupLayout(registrasiPeminjam);
        registrasiPeminjam.setLayout(registrasiPeminjamLayout);
        registrasiPeminjamLayout.setHorizontalGroup(
            registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrasiPeminjamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regisPeminjamTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(registrasiPeminjamLayout.createSequentialGroup()
                        .addGroup(registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(l_telp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l_alamat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l_Id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(l_nama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l_maksPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inpMaksPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(registrasiPeminjamLayout.createSequentialGroup()
                                .addGroup(registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inpTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(inpId, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(inpAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(inpNama, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inpJenisId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrasiPeminjamLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKosongkanData, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnSimpanData, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        registrasiPeminjamLayout.setVerticalGroup(
            registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrasiPeminjamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(regisPeminjamTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrasiPeminjamLayout.createSequentialGroup()
                        .addGroup(registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registrasiPeminjamLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(inpJenisId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addGroup(registrasiPeminjamLayout.createSequentialGroup()
                                .addComponent(inpNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inpId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(11, 11, 11)))
                        .addComponent(inpAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpTelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(registrasiPeminjamLayout.createSequentialGroup()
                        .addComponent(l_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(l_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(l_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(l_telp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGroup(registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l_maksPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(inpMaksPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE))
                .addGap(255, 255, 255)
                .addGroup(registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanData, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKosongkanData, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        l_nama.getAccessibleContext().setAccessibleName("");
        l_nama.getAccessibleContext().setAccessibleDescription("");
        inpNama.getAccessibleContext().setAccessibleName("");
        inpNama.getAccessibleContext().setAccessibleDescription("");
        l_Id.getAccessibleContext().setAccessibleName("");
        l_Id.getAccessibleContext().setAccessibleDescription("");
        inpId.getAccessibleContext().setAccessibleName("");
        inpId.getAccessibleContext().setAccessibleDescription("");
        inpJenisId.getAccessibleContext().setAccessibleName("");
        inpJenisId.getAccessibleContext().setAccessibleDescription("");
        l_alamat.getAccessibleContext().setAccessibleName("");
        l_alamat.getAccessibleContext().setAccessibleDescription("");
        inpAlamat.getAccessibleContext().setAccessibleName("");
        inpAlamat.getAccessibleContext().setAccessibleDescription("");
        l_telp.getAccessibleContext().setAccessibleName("");
        l_telp.getAccessibleContext().setAccessibleDescription("");
        inpTelp.getAccessibleContext().setAccessibleName("");
        inpTelp.getAccessibleContext().setAccessibleDescription("");
        l_maksPinjam.getAccessibleContext().setAccessibleName("");
        l_maksPinjam.getAccessibleContext().setAccessibleDescription("");
        inpMaksPinjam.getAccessibleContext().setAccessibleName("");
        inpMaksPinjam.getAccessibleContext().setAccessibleDescription("");

        formContainer.add(registrasiPeminjam, "card1");

        registKoleksiTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registKoleksiTitle.setText("Registrasi Data Koleksi");

        l_judulBuku.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_judulBuku.setText("Judul / Title");

        inpJudulBuku.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        inpJudulBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpJudulBukuActionPerformed(evt);
            }
        });

        l_penerbit.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_penerbit.setText("Penerbit");

        inpPenerbit.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        inpPenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpPenerbitActionPerformed(evt);
            }
        });

        l_judulBuku4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_judulBuku4.setText("Tipe Koleksi");

        inp_regTipeKoleksi.add(inpTipeBuku);
        inpTipeBuku.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inpTipeBuku.setSelected(true);
        inpTipeBuku.setText("Buku");
        inpTipeBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpTipeBukuActionPerformed(evt);
            }
        });

        inp_regTipeKoleksi.add(inpTipeMajalah);
        inpTipeMajalah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inpTipeMajalah.setText("Majalah");
        inpTipeMajalah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpTipeMajalahActionPerformed(evt);
            }
        });

        inp_regTipeKoleksi.add(inpTipeDisk);
        inpTipeDisk.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inpTipeDisk.setText("Disk");
        inpTipeDisk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpTipeDiskActionPerformed(evt);
            }
        });

        l_isbnIssn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_isbnIssn.setText("ISBN / ISSN");

        inpIsbnIssn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        inpIsbnIssn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpIsbnIssnActionPerformed(evt);
            }
        });

        l_jmlHalaman.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_jmlHalaman.setText("Jml. Halaman");

        inpJmlHalaman.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        l_volume.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_volume.setText("Volume");
        l_volume.setEnabled(false);

        inpVolume.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inpVolume.setEnabled(false);

        l_seri.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_seri.setText("Seri");
        l_seri.setEnabled(false);

        inpSeri.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inpSeri.setEnabled(false);

        l_format.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_format.setText("Format");
        l_format.setEnabled(false);

        inpFormat.setEnabled(false);
        inpFormat.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        inpFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpFormatActionPerformed(evt);
            }
        });

        btnSimpanBuku.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSimpanBuku.setText("Simpan");
        btnSimpanBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanBukuActionPerformed(evt);
            }
        });

        btlKosongkan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btlKosongkan.setText("Kosongkan");
        btlKosongkan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btlKosongkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlKosongkanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registrasiKoleksiLayout = new javax.swing.GroupLayout(registrasiKoleksi);
        registrasiKoleksi.setLayout(registrasiKoleksiLayout);
        registrasiKoleksiLayout.setHorizontalGroup(
            registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrasiKoleksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrasiKoleksiLayout.createSequentialGroup()
                        .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registrasiKoleksiLayout.createSequentialGroup()
                                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(registrasiKoleksiLayout.createSequentialGroup()
                                        .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(l_judulBuku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                                .addComponent(l_penerbit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(l_isbnIssn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(l_judulBuku4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(l_jmlHalaman, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(registrasiKoleksiLayout.createSequentialGroup()
                                        .addComponent(l_volume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(10, 10, 10)))
                                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(inpJudulBuku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(inpTipeBuku)
                                            .addComponent(inpPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(inpTipeMajalah)
                                            .addComponent(inpTipeDisk)
                                            .addComponent(inpIsbnIssn, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(inpJmlHalaman, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inpVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(registrasiKoleksiLayout.createSequentialGroup()
                                .addComponent(l_seri, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(inpSeri, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(registKoleksiTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(registrasiKoleksiLayout.createSequentialGroup()
                                .addComponent(l_format, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inpFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrasiKoleksiLayout.createSequentialGroup()
                        .addComponent(btlKosongkan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(btnSimpanBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        registrasiKoleksiLayout.setVerticalGroup(
            registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrasiKoleksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registKoleksiTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inpJudulBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(l_judulBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l_penerbit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inpPenerbit, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inpIsbnIssn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_isbnIssn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inpTipeBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_judulBuku4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addComponent(inpTipeMajalah, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(inpTipeDisk, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrasiKoleksiLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(inpJmlHalaman, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(l_jmlHalaman, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrasiKoleksiLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(inpVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(l_volume, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_seri, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpSeri, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_format, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btlKosongkan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        formContainer.add(registrasiKoleksi, "card2");

        menuBarMain.setForeground(new java.awt.Color(153, 204, 255));

        menuBar_info.setText("Informasi");
        menuBarMain.add(menuBar_info);

        setJMenuBar(menuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(menuContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(formContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regPeminjamActionPerformed
        formCards.show(formContainer, "card1");
    }//GEN-LAST:event_btn_regPeminjamActionPerformed

    private void btn_regKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regKoleksiActionPerformed
        formCards.show(formContainer, "card2");
    }//GEN-LAST:event_btn_regKoleksiActionPerformed

    private void btnKosongkanDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKosongkanDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKosongkanDataActionPerformed

    private void btnSimpanDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanDataActionPerformed
        
    }//GEN-LAST:event_btnSimpanDataActionPerformed

    private void inpTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpTelpActionPerformed

    private void inpAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpAlamatActionPerformed

    private void inpJenisIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpJenisIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpJenisIdActionPerformed

    private void inpIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpIdActionPerformed

    private void inpNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpNamaActionPerformed

    private void btlKosongkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlKosongkanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btlKosongkanActionPerformed

    private void btnSimpanBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanBukuActionPerformed

    private void inpFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpFormatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpFormatActionPerformed

    private void inpIsbnIssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpIsbnIssnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpIsbnIssnActionPerformed

    private void inpTipeDiskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpTipeDiskActionPerformed
        setFalseAllTipeKoleksi();

        l_format.setEnabled(true);
        inpFormat.setEnabled(true);
    }//GEN-LAST:event_inpTipeDiskActionPerformed

    private void inpTipeMajalahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpTipeMajalahActionPerformed
        setFalseAllTipeKoleksi();

        l_volume.setEnabled(true);
        inpVolume.setEnabled(true);
        l_seri.setEnabled(true);
        inpSeri.setEnabled(true);
    }//GEN-LAST:event_inpTipeMajalahActionPerformed

    private void inpTipeBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpTipeBukuActionPerformed
        setFalseAllTipeKoleksi();

        l_jmlHalaman.setEnabled(true);
        inpJmlHalaman.setEnabled(true);
    }//GEN-LAST:event_inpTipeBukuActionPerformed

    private void inpPenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpPenerbitActionPerformed
    }//GEN-LAST:event_inpPenerbitActionPerformed

    private void inpJudulBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpJudulBukuActionPerformed
    }//GEN-LAST:event_inpJudulBukuActionPerformed

    private void setFalseAllTipeKoleksi() {
        l_jmlHalaman.setEnabled(false);
        inpJmlHalaman.setEnabled(false);
        l_volume.setEnabled(false);
        inpVolume.setEnabled(false);
        l_seri.setEnabled(false);
        inpSeri.setEnabled(false);
        l_format.setEnabled(false);
        inpFormat.setEnabled(false);}

    private void createComponentMap() {
        components = new HashMap<String, Component>();
        Component[] allComponents = formContainer.getComponents();
        for (Component component : allComponents) {
            components.put(component.getName(), component);
        }
    }

    public Component getComponent(String name) {
        if (components.containsKey(name)) {
                return components.get(name);
        } else {
            return null;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btlKosongkan;
    private javax.swing.JButton btnKosongkanData;
    private javax.swing.JButton btnSimpanBuku;
    private javax.swing.JButton btnSimpanData;
    private javax.swing.JButton btn_regKoleksi;
    private javax.swing.JButton btn_regPeminjam;
    private javax.swing.JPanel formContainer;
    private java.awt.TextField inpAlamat;
    private java.awt.TextField inpFormat;
    private java.awt.TextField inpId;
    private java.awt.TextField inpIsbnIssn;
    private javax.swing.JComboBox<String> inpJenisId;
    private javax.swing.JSpinner inpJmlHalaman;
    private java.awt.TextField inpJudulBuku;
    private javax.swing.JSpinner inpMaksPinjam;
    private java.awt.TextField inpNama;
    private java.awt.TextField inpPenerbit;
    private javax.swing.JSpinner inpSeri;
    private java.awt.TextField inpTelp;
    private javax.swing.JRadioButton inpTipeBuku;
    private javax.swing.JRadioButton inpTipeDisk;
    private javax.swing.JRadioButton inpTipeMajalah;
    private javax.swing.JSpinner inpVolume;
    private javax.swing.ButtonGroup inp_regTipeKoleksi;
    private javax.swing.JLabel l_Id;
    private javax.swing.JLabel l_alamat;
    private javax.swing.JLabel l_format;
    private javax.swing.JLabel l_isbnIssn;
    private javax.swing.JLabel l_jmlHalaman;
    private javax.swing.JLabel l_judulBuku;
    private javax.swing.JLabel l_judulBuku4;
    private javax.swing.JLabel l_maksPinjam;
    private javax.swing.JLabel l_nama;
    private javax.swing.JLabel l_penerbit;
    private javax.swing.JLabel l_seri;
    private javax.swing.JLabel l_telp;
    private javax.swing.JLabel l_volume;
    private javax.swing.JMenuBar menuBarMain;
    private javax.swing.JMenu menuBar_info;
    private javax.swing.JPanel menuContainer;
    private javax.swing.JLabel menuTitle;
    private javax.swing.JLabel regisPeminjamTitle;
    private javax.swing.JLabel registKoleksiTitle;
    private javax.swing.JPanel registrasiKoleksi;
    private javax.swing.JPanel registrasiPeminjam;
    // End of variables declaration//GEN-END:variables
}
