/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbol.gui.app;

import javax.swing.*;
import java.awt.*;
import java.util.HashMap;
import java.util.Objects;

/**
 *
 * @author narwa
 */
public class App extends javax.swing.JFrame {

    private final CardLayout formCards;
    private HashMap<String, Component> components;
    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        setTitle("Sistem Manajemen Perpustakaan");
        setIconImage(
          new ImageIcon(
            Objects.requireNonNull(
              getClass().getResource("/images/bookIcon.png"))
          ).getImage()
        );
        formCards = (CardLayout) formContainer.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inp_regTipeKoleksi = new javax.swing.ButtonGroup();
        menuContainer = new javax.swing.JPanel();
        menuTitle = new javax.swing.JLabel();
        b_regPeminjam = new javax.swing.JButton();
        b_regKoleksi = new javax.swing.JButton();
        formContainer = new javax.swing.JPanel();
        registrasiPeminjam = new javax.swing.JPanel();
        regisPeminjamTitle = new javax.swing.JLabel();
        l_nama = new javax.swing.JLabel();
        i_nama = new java.awt.TextField();
        l_noId = new javax.swing.JLabel();
        i_noId = new java.awt.TextField();
        i_jenisNoId = new javax.swing.JComboBox<>();
        l_alamat = new javax.swing.JLabel();
        i_alamat = new java.awt.TextField();
        l_telp = new javax.swing.JLabel();
        i_telp = new java.awt.TextField();
        l_maksPinjam = new javax.swing.JLabel();
        i_maksPinjam = new javax.swing.JSpinner();
        b_simpanRegPeminjam = new javax.swing.JButton();
        b_kosongkanRegPeminjam = new javax.swing.JButton();
        registrasiKoleksi = new javax.swing.JPanel();
        registKoleksiTitle = new javax.swing.JLabel();
        l_judulKoleksi = new javax.swing.JLabel();
        i_judulKoleksi = new java.awt.TextField();
        l_penerbit = new javax.swing.JLabel();
        i_penerbit = new java.awt.TextField();
        l_judulBuku4 = new javax.swing.JLabel();
        i_jenisBuku = new javax.swing.JRadioButton();
        i_jenisMajalah = new javax.swing.JRadioButton();
        i_jenisDisk = new javax.swing.JRadioButton();
        l_isbnIssn = new javax.swing.JLabel();
        i_isnIssn = new java.awt.TextField();
        l_jmlHalaman = new javax.swing.JLabel();
        i_jmlHalaman = new javax.swing.JSpinner();
        l_volume = new javax.swing.JLabel();
        i_volume = new javax.swing.JSpinner();
        l_seri = new javax.swing.JLabel();
        i_seri = new javax.swing.JSpinner();
        l_format = new javax.swing.JLabel();
        i_format = new java.awt.TextField();
        b_simpanRegKoleksi = new javax.swing.JButton();
        b_kosongkanRegKoleksi = new javax.swing.JButton();
        menuBarMain = new javax.swing.JMenuBar();
        menuBar_info = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Manajemen Data Perpustakaan");
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1280, 720));
        setMinimumSize(new java.awt.Dimension(960, 540));

        menuContainer.setBackground(new java.awt.Color(153, 204, 255));

        menuTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuTitle.setForeground(new java.awt.Color(51, 102, 255));
        menuTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTitle.setText("<html>Sistem Manajemen<br/>Perpustakaan</html>");

        b_regPeminjam.setBackground(new java.awt.Color(153, 153, 255));
        b_regPeminjam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_regPeminjam.setForeground(new java.awt.Color(255, 255, 255));
        b_regPeminjam.setText("Registrasi Peminjam");
        b_regPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_regPeminjamActionPerformed(evt);
            }
        });

        b_regKoleksi.setBackground(new java.awt.Color(153, 153, 255));
        b_regKoleksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_regKoleksi.setForeground(new java.awt.Color(255, 255, 255));
        b_regKoleksi.setText("Registrasi Koleksi");
        b_regKoleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_regKoleksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuContainerLayout = new javax.swing.GroupLayout(menuContainer);
        menuContainer.setLayout(menuContainerLayout);
        menuContainerLayout.setHorizontalGroup(
            menuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(b_regPeminjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_regKoleksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuContainerLayout.setVerticalGroup(
            menuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_regPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_regKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(331, Short.MAX_VALUE))
        );

        formContainer.setBackground(new java.awt.Color(255, 255, 255));
        formContainer.setLayout(new java.awt.CardLayout());

        registrasiPeminjam.setPreferredSize(new java.awt.Dimension(700, 540));

        regisPeminjamTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        regisPeminjamTitle.setText("Registrasi Data Peminjam");

        l_nama.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_nama.setText("Nama Lengkap");
        l_nama.setMaximumSize(new java.awt.Dimension(150, 25));
        l_nama.setMinimumSize(new java.awt.Dimension(150, 25));

        i_nama.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        i_nama.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_nama.setName(""); // NOI18N
        i_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_namaActionPerformed(evt);
            }
        });

        l_noId.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_noId.setText("Nomor Identitas");
        l_noId.setMaximumSize(new java.awt.Dimension(150, 25));
        l_noId.setMinimumSize(new java.awt.Dimension(150, 25));

        i_noId.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_noId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_noIdActionPerformed(evt);
            }
        });

        i_jenisNoId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        i_jenisNoId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIM", "NIP", "NIK" }));
        i_jenisNoId.setToolTipText("Jenis Nomor Identitas");
        i_jenisNoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_jenisNoIdActionPerformed(evt);
            }
        });

        l_alamat.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_alamat.setText("Alamat");
        l_alamat.setMaximumSize(new java.awt.Dimension(150, 25));
        l_alamat.setMinimumSize(new java.awt.Dimension(150, 25));

        i_alamat.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_alamatActionPerformed(evt);
            }
        });

        l_telp.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_telp.setText("Nomor Telepon");
        l_telp.setMaximumSize(new java.awt.Dimension(150, 25));
        l_telp.setMinimumSize(new java.awt.Dimension(150, 25));

        i_telp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_telp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_telpActionPerformed(evt);
            }
        });

        l_maksPinjam.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_maksPinjam.setText("Maks. Pinjaman");
        l_maksPinjam.setMaximumSize(new java.awt.Dimension(150, 25));
        l_maksPinjam.setMinimumSize(new java.awt.Dimension(150, 25));

        i_maksPinjam.setModel(new javax.swing.SpinnerNumberModel(1, 0, 10, 1));

        b_simpanRegPeminjam.setBackground(new java.awt.Color(51, 204, 0));
        b_simpanRegPeminjam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_simpanRegPeminjam.setForeground(new java.awt.Color(255, 255, 255));
        b_simpanRegPeminjam.setText("Simpan");
        b_simpanRegPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_simpanRegPeminjamActionPerformed(evt);
            }
        });

        b_kosongkanRegPeminjam.setBackground(new java.awt.Color(255, 102, 102));
        b_kosongkanRegPeminjam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_kosongkanRegPeminjam.setForeground(new java.awt.Color(255, 255, 255));
        b_kosongkanRegPeminjam.setText("Kosongkan");
        b_kosongkanRegPeminjam.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b_kosongkanRegPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_kosongkanRegPeminjamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registrasiPeminjamLayout = new javax.swing.GroupLayout(registrasiPeminjam);
        registrasiPeminjam.setLayout(registrasiPeminjamLayout);
        registrasiPeminjamLayout.setHorizontalGroup(
            registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrasiPeminjamLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_kosongkanRegPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b_simpanRegPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(registrasiPeminjamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regisPeminjamTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(registrasiPeminjamLayout.createSequentialGroup()
                        .addGroup(registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(l_telp, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(l_noId, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(l_alamat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(l_maksPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(l_nama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addGroup(registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registrasiPeminjamLayout.createSequentialGroup()
                                .addComponent(i_noId, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(i_jenisNoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(i_maksPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(i_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(i_telp, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(i_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        registrasiPeminjamLayout.setVerticalGroup(
            registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrasiPeminjamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(regisPeminjamTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_noId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i_jenisNoId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i_noId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_telp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i_telp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l_maksPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i_maksPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                .addGroup(registrasiPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_simpanRegPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_kosongkanRegPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        l_nama.getAccessibleContext().setAccessibleName("");
        l_nama.getAccessibleContext().setAccessibleDescription("");
        i_nama.getAccessibleContext().setAccessibleName("");
        i_nama.getAccessibleContext().setAccessibleDescription("");
        l_noId.getAccessibleContext().setAccessibleName("");
        l_noId.getAccessibleContext().setAccessibleDescription("");
        i_noId.getAccessibleContext().setAccessibleName("");
        i_noId.getAccessibleContext().setAccessibleDescription("");
        i_jenisNoId.getAccessibleContext().setAccessibleName("");
        i_jenisNoId.getAccessibleContext().setAccessibleDescription("");
        l_alamat.getAccessibleContext().setAccessibleName("");
        l_alamat.getAccessibleContext().setAccessibleDescription("");
        i_alamat.getAccessibleContext().setAccessibleName("");
        i_alamat.getAccessibleContext().setAccessibleDescription("");
        l_telp.getAccessibleContext().setAccessibleName("");
        l_telp.getAccessibleContext().setAccessibleDescription("");
        i_telp.getAccessibleContext().setAccessibleName("");
        i_telp.getAccessibleContext().setAccessibleDescription("");
        l_maksPinjam.getAccessibleContext().setAccessibleName("");
        l_maksPinjam.getAccessibleContext().setAccessibleDescription("");
        i_maksPinjam.getAccessibleContext().setAccessibleName("");
        i_maksPinjam.getAccessibleContext().setAccessibleDescription("");

        formContainer.add(registrasiPeminjam, "card1");

        registrasiKoleksi.setMaximumSize(new java.awt.Dimension(150, 25));
        registrasiKoleksi.setMinimumSize(new java.awt.Dimension(150, 25));

        registKoleksiTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registKoleksiTitle.setText("Registrasi Data Koleksi");

        l_judulKoleksi.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_judulKoleksi.setText("Judul / Title");
        l_judulKoleksi.setMaximumSize(new java.awt.Dimension(150, 25));
        l_judulKoleksi.setMinimumSize(new java.awt.Dimension(150, 25));

        i_judulKoleksi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_judulKoleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_judulKoleksiActionPerformed(evt);
            }
        });

        l_penerbit.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_penerbit.setText("Penerbit");
        l_penerbit.setMaximumSize(new java.awt.Dimension(150, 25));
        l_penerbit.setMinimumSize(new java.awt.Dimension(150, 25));

        i_penerbit.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_penerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_penerbitActionPerformed(evt);
            }
        });

        l_judulBuku4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_judulBuku4.setText("Tipe Koleksi");
        l_judulBuku4.setMaximumSize(new java.awt.Dimension(150, 25));
        l_judulBuku4.setMinimumSize(new java.awt.Dimension(150, 25));

        inp_regTipeKoleksi.add(i_jenisBuku);
        i_jenisBuku.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        i_jenisBuku.setSelected(true);
        i_jenisBuku.setText("Buku");
        i_jenisBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_jenisBukuActionPerformed(evt);
            }
        });

        inp_regTipeKoleksi.add(i_jenisMajalah);
        i_jenisMajalah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        i_jenisMajalah.setText("Majalah");
        i_jenisMajalah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_jenisMajalahActionPerformed(evt);
            }
        });

        inp_regTipeKoleksi.add(i_jenisDisk);
        i_jenisDisk.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        i_jenisDisk.setText("Disk");
        i_jenisDisk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_jenisDiskActionPerformed(evt);
            }
        });

        l_isbnIssn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_isbnIssn.setText("ISBN / ISSN");
        l_isbnIssn.setMaximumSize(new java.awt.Dimension(150, 25));
        l_isbnIssn.setMinimumSize(new java.awt.Dimension(150, 25));

        i_isnIssn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_isnIssn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_isnIssnActionPerformed(evt);
            }
        });

        l_jmlHalaman.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_jmlHalaman.setText("Jml. Halaman");
        l_jmlHalaman.setMaximumSize(new java.awt.Dimension(150, 25));
        l_jmlHalaman.setMinimumSize(new java.awt.Dimension(150, 25));

        i_jmlHalaman.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        l_volume.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_volume.setText("Volume");
        l_volume.setEnabled(false);
        l_volume.setMaximumSize(new java.awt.Dimension(150, 25));
        l_volume.setMinimumSize(new java.awt.Dimension(150, 25));

        i_volume.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        i_volume.setEnabled(false);

        l_seri.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_seri.setText("Seri");
        l_seri.setEnabled(false);
        l_seri.setMaximumSize(new java.awt.Dimension(150, 25));
        l_seri.setMinimumSize(new java.awt.Dimension(150, 25));

        i_seri.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        i_seri.setEnabled(false);

        l_format.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l_format.setText("Format");
        l_format.setEnabled(false);
        l_format.setMaximumSize(new java.awt.Dimension(150, 25));
        l_format.setMinimumSize(new java.awt.Dimension(150, 25));

        i_format.setEnabled(false);
        i_format.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        i_format.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_formatActionPerformed(evt);
            }
        });

        b_simpanRegKoleksi.setBackground(new java.awt.Color(51, 204, 0));
        b_simpanRegKoleksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_simpanRegKoleksi.setForeground(new java.awt.Color(255, 255, 255));
        b_simpanRegKoleksi.setText("Simpan");
        b_simpanRegKoleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_simpanRegKoleksiActionPerformed(evt);
            }
        });

        b_kosongkanRegKoleksi.setBackground(new java.awt.Color(255, 102, 102));
        b_kosongkanRegKoleksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_kosongkanRegKoleksi.setForeground(new java.awt.Color(255, 255, 255));
        b_kosongkanRegKoleksi.setText("Kosongkan");
        b_kosongkanRegKoleksi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b_kosongkanRegKoleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_kosongkanRegKoleksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registrasiKoleksiLayout = new javax.swing.GroupLayout(registrasiKoleksi);
        registrasiKoleksi.setLayout(registrasiKoleksiLayout);
        registrasiKoleksiLayout.setHorizontalGroup(
            registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrasiKoleksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrasiKoleksiLayout.createSequentialGroup()
                        .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registKoleksiTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(registrasiKoleksiLayout.createSequentialGroup()
                                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(l_penerbit, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(l_isbnIssn, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(l_judulBuku4, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(l_jmlHalaman, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(l_volume, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(l_judulKoleksi, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                    .addComponent(l_seri, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_format, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(i_judulKoleksi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(i_jenisBuku)
                                            .addComponent(i_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(i_jenisMajalah)
                                            .addComponent(i_jenisDisk)
                                            .addComponent(i_isnIssn, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(i_jmlHalaman, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(i_volume, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(i_seri, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(i_format, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(148, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrasiKoleksiLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(b_kosongkanRegKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b_simpanRegKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))))
        );
        registrasiKoleksiLayout.setVerticalGroup(
            registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrasiKoleksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registKoleksiTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(i_judulKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_judulKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(i_isnIssn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_isbnIssn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(i_jenisBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_judulBuku4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(i_jenisMajalah, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(i_jenisDisk, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrasiKoleksiLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(i_jmlHalaman, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(l_jmlHalaman, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrasiKoleksiLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(i_volume, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(l_volume, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_seri, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i_seri, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_format, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i_format, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(registrasiKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_simpanRegKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_kosongkanRegKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        formContainer.add(registrasiKoleksi, "card2");

        menuBarMain.setForeground(new java.awt.Color(153, 204, 255));

        menuBar_info.setText("Informasi");
        menuBarMain.add(menuBar_info);

        setJMenuBar(menuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(menuContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(formContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Mengganti frame formulir ke formulir registrasi data peminjam.
     * */
    private void b_regPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_regPeminjamActionPerformed
        formCards.show(formContainer, "card1");
    }//GEN-LAST:event_b_regPeminjamActionPerformed

    /**
     * Mengganti frame formulir ke formulir registrasi data koleksi.
     * */
    private void b_regKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_regKoleksiActionPerformed
        formCards.show(formContainer, "card2");
    }//GEN-LAST:event_b_regKoleksiActionPerformed

    /**
     * Mengosongkan dan mengatur nilai ke awal pada formulir registrasi data peminjam.
     * */
    private void b_kosongkanRegPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_kosongkanPeminjamActionPerformed
        i_nama.setText("");
        i_noId.setText("");
        i_jenisNoId.setSelectedIndex(0);
        i_alamat.setText("");
        i_telp.setText("");
        i_maksPinjam.setValue(1);
    }//GEN-LAST:event_b_kosongkanPeminjamActionPerformed

    private void b_simpanRegPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_simpanPeminjamBaruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_simpanPeminjamBaruActionPerformed

    private void i_telpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_telpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_telpActionPerformed

    private void i_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_alamatActionPerformed

    private void i_jenisNoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_jenisNoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_jenisNoIdActionPerformed

    private void i_noIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_noIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_noIdActionPerformed

    private void i_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_namaActionPerformed

    /**
     * Mengosongkan dan mengatur nilai ke awal pada formulir registrasi data koleksi.
     * */
    private void b_kosongkanRegKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlKosongkanActionPerformed
        i_judulKoleksi.setText("");
        i_penerbit.setText("");
        i_isnIssn.setText("");
        inp_regTipeKoleksi.setSelected(i_jenisBuku.getModel(), true);
        i_jmlHalaman.setValue(1);
        i_volume.setValue(1);
        i_seri.setValue(1);
        i_format.setText("");
    }//GEN-LAST:event_btlKosongkanActionPerformed

    private void b_simpanRegKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanBukuActionPerformed

    private void i_formatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_formatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_formatActionPerformed

    private void i_isnIssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_isnIssnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_isnIssnActionPerformed

    /**
     * Mengaktifkan input field disk (label dan input: FORMAT)
     * */
    private void i_jenisDiskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_jenisDiskActionPerformed
        setFalseAllTipeKoleksi();

        l_format.setEnabled(true);
        i_format.setEnabled(true);
    }//GEN-LAST:event_i_jenisDiskActionPerformed

    /**
     * Mengaktifkan input field majalah (label dan input: VOLUME, SERI).
     * */
    private void i_jenisMajalahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_jenisMajalahActionPerformed
        setFalseAllTipeKoleksi();

        l_volume.setEnabled(true);
        i_volume.setEnabled(true);
        l_seri.setEnabled(true);
        i_seri.setEnabled(true);
    }//GEN-LAST:event_i_jenisMajalahActionPerformed

    /**
     * Mengaktifkan input field buku (label dan input: HALAMAN).
     * */
    private void i_jenisBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_jenisBukuActionPerformed
        setFalseAllTipeKoleksi();

        l_jmlHalaman.setEnabled(true);
        i_jmlHalaman.setEnabled(true);
    }//GEN-LAST:event_i_jenisBukuActionPerformed

    private void i_penerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_penerbitActionPerformed
    }//GEN-LAST:event_i_penerbitActionPerformed

    private void i_judulKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_judulKoleksiActionPerformed
    }//GEN-LAST:event_i_judulKoleksiActionPerformed

    /* Visibility functions */

    /**
     * Menyetel seluruh fields spesial dalam formulir registrasi koleksi ke mati (disabled).
     * */
    private void setFalseAllTipeKoleksi() {
        l_jmlHalaman.setEnabled(false);
        i_jmlHalaman.setEnabled(false);
        l_volume.setEnabled(false);
        i_volume.setEnabled(false);
        l_seri.setEnabled(false);
        i_seri.setEnabled(false);
        l_format.setEnabled(false);
        i_format.setEnabled(false);
    }

    /**
     * Metode penjalan kelas.
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Mengatur look and feels tampilan jendela menjadi Nimbus */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new App().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_kosongkanRegKoleksi;
    private javax.swing.JButton b_kosongkanRegPeminjam;
    private javax.swing.JButton b_regKoleksi;
    private javax.swing.JButton b_regPeminjam;
    private javax.swing.JButton b_simpanRegKoleksi;
    private javax.swing.JButton b_simpanRegPeminjam;
    private javax.swing.JPanel formContainer;
    private java.awt.TextField i_alamat;
    private java.awt.TextField i_format;
    private java.awt.TextField i_isnIssn;
    private javax.swing.JRadioButton i_jenisBuku;
    private javax.swing.JRadioButton i_jenisDisk;
    private javax.swing.JRadioButton i_jenisMajalah;
    private javax.swing.JComboBox<String> i_jenisNoId;
    private javax.swing.JSpinner i_jmlHalaman;
    private java.awt.TextField i_judulKoleksi;
    private javax.swing.JSpinner i_maksPinjam;
    private java.awt.TextField i_nama;
    private java.awt.TextField i_noId;
    private java.awt.TextField i_penerbit;
    private javax.swing.JSpinner i_seri;
    private java.awt.TextField i_telp;
    private javax.swing.JSpinner i_volume;
    private javax.swing.ButtonGroup inp_regTipeKoleksi;
    private javax.swing.JLabel l_alamat;
    private javax.swing.JLabel l_format;
    private javax.swing.JLabel l_isbnIssn;
    private javax.swing.JLabel l_jmlHalaman;
    private javax.swing.JLabel l_judulBuku4;
    private javax.swing.JLabel l_judulKoleksi;
    private javax.swing.JLabel l_maksPinjam;
    private javax.swing.JLabel l_nama;
    private javax.swing.JLabel l_noId;
    private javax.swing.JLabel l_penerbit;
    private javax.swing.JLabel l_seri;
    private javax.swing.JLabel l_telp;
    private javax.swing.JLabel l_volume;
    private javax.swing.JMenuBar menuBarMain;
    private javax.swing.JMenu menuBar_info;
    private javax.swing.JPanel menuContainer;
    private javax.swing.JLabel menuTitle;
    private javax.swing.JLabel regisPeminjamTitle;
    private javax.swing.JLabel registKoleksiTitle;
    private javax.swing.JPanel registrasiKoleksi;
    private javax.swing.JPanel registrasiPeminjam;
    // End of variables declaration//GEN-END:variables
}
