package gui;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import backend.*;
import backend.koleksi.Buku;
import backend.koleksi.Disk;
import backend.koleksi.Koleksi;
import backend.koleksi.Majalah;
import backend.peminjam.Peminjam;

import javax.swing.*;
import java.awt.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * @author narwa
 */
public class FormTransaksi extends javax.swing.JFrame {

	private final Color I_RED = new Color(0xFF5959);
	/**
	 * Atribut kelas ini menyimpan data dari data perpustakaan.
	 */
	public DataPerpus dataPerpus;
	private List<Koleksi> keranjangKoleksi = new ArrayList<>();
	private Peminjam currentPeminjam;
	private Koleksi currentKoleksi;

	/**
	 * Creates new form FormTransaksi
	 */
	public FormTransaksi(DataPerpus dataPerpus) {
		this.dataPerpus = new DataPerpus();
		initComponents();
		setTitle("Input Transaksi Peminjaman");

		/* Mengatur icon/gambar judul pada window frame */
		setIconImage(
			new ImageIcon(
				Objects.requireNonNull(
					getClass().getResource("/images/bookIcon.png"))
			).getImage()
		);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		panel_Koleksi = new javax.swing.JPanel();
		b_cekKoleksi = new javax.swing.JButton();
		i_judulKoleksi = new java.awt.TextField();
		i_kodeKoleksi = new java.awt.TextField();
		l_pencarianKoleksi = new javax.swing.JLabel();
		f_judulKoleksi = new java.awt.TextField();
		l_nama = new javax.swing.JLabel();
		f_penerbit = new java.awt.TextField();
		l_penerbit = new javax.swing.JLabel();
		l_isbnIssn = new javax.swing.JLabel();
		f_isbnIssn = new java.awt.TextField();
		f_tipeKoleksi = new java.awt.TextField();
		l_tipeKoleksi = new javax.swing.JLabel();
		b_tambahKoleksi = new javax.swing.JButton();
		b_hapusKoleksi = new javax.swing.JButton();
		panel_PeminjamDeadline = new javax.swing.JPanel();
		l_pencarianPeminjam = new javax.swing.JLabel();
		b_cekPeminjam = new javax.swing.JButton();
		i_namaPeminjam = new java.awt.TextField();
		i_kodePeminjam = new java.awt.TextField();
		l_namaPeminjam = new javax.swing.JLabel();
		f_namaPeminjam = new java.awt.TextField();
		f_maksPinjam = new java.awt.TextField();
		l_lamaPinjam = new javax.swing.JLabel();
		i_lamaPinjam = new javax.swing.JComboBox<>();
		l_dari = new javax.swing.JLabel();
		f_dari = new java.awt.TextField();
		b_kosongkanTransaksi = new javax.swing.JButton();
		b_konfirmasiTransaksi = new javax.swing.JButton();
		b_kembali = new javax.swing.JButton();
		panel_keranjangTable = new javax.swing.JPanel();
		scrollPane_tabelKeranjang = new javax.swing.JScrollPane();
		tabelKeranjang = new javax.swing.JTable();
		l_tabelKeranjang = new javax.swing.JLabel();
		panel_transaksiTable = new javax.swing.JPanel();
		scrollPane_tabelTransaksi = new javax.swing.JScrollPane();
		tabelTransaksi = new javax.swing.JTable();
		l_tabelTransaksi = new javax.swing.JLabel();

		setMaximumSize(new java.awt.Dimension(960, 540));
		setMinimumSize(new java.awt.Dimension(960, 540));
		setResizable(false);

		panel_Koleksi.setBackground(new java.awt.Color(153, 204, 255));
		panel_Koleksi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		panel_Koleksi.setPreferredSize(new java.awt.Dimension(480, 270));

		b_cekKoleksi.setText("Cari");
		b_cekKoleksi.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				b_cekKoleksiActionPerformed(evt);
			}
		});

		i_judulKoleksi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
		i_judulKoleksi.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				i_judulKoleksiFocusLost(evt);
			}
		});
		i_judulKoleksi.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				i_judulKoleksiActionPerformed(evt);
			}
		});

		i_kodeKoleksi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
		i_kodeKoleksi.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				i_kodeKoleksiFocusLost(evt);
			}
		});
		i_kodeKoleksi.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				i_kodeKoleksiActionPerformed(evt);
			}
		});

		l_pencarianKoleksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		l_pencarianKoleksi.setForeground(new java.awt.Color(0, 0, 0));
		l_pencarianKoleksi.setText("Pencarian Koleksi");

		f_judulKoleksi.setEnabled(false);
		f_judulKoleksi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
		f_judulKoleksi.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				f_judulKoleksiFocusLost(evt);
			}
		});
		f_judulKoleksi.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				f_judulKoleksiActionPerformed(evt);
			}
		});

		l_nama.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
		l_nama.setForeground(new java.awt.Color(51, 51, 51));
		l_nama.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		l_nama.setText("Judul");
		l_nama.setToolTipText("");
		l_nama.setMaximumSize(new java.awt.Dimension(150, 25));
		l_nama.setMinimumSize(new java.awt.Dimension(150, 25));

		f_penerbit.setEnabled(false);
		f_penerbit.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
		f_penerbit.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				f_penerbitFocusLost(evt);
			}
		});
		f_penerbit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				f_penerbitActionPerformed(evt);
			}
		});

		l_penerbit.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
		l_penerbit.setForeground(new java.awt.Color(51, 51, 51));
		l_penerbit.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		l_penerbit.setText("Penerbit");
		l_penerbit.setToolTipText("");
		l_penerbit.setMaximumSize(new java.awt.Dimension(150, 25));
		l_penerbit.setMinimumSize(new java.awt.Dimension(150, 25));

		l_isbnIssn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
		l_isbnIssn.setForeground(new java.awt.Color(51, 51, 51));
		l_isbnIssn.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		l_isbnIssn.setText("ISSN/ISBN");
		l_isbnIssn.setToolTipText("");
		l_isbnIssn.setMaximumSize(new java.awt.Dimension(150, 25));
		l_isbnIssn.setMinimumSize(new java.awt.Dimension(150, 25));

		f_isbnIssn.setEnabled(false);
		f_isbnIssn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
		f_isbnIssn.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				f_isbnIssnFocusLost(evt);
			}
		});
		f_isbnIssn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				f_isbnIssnActionPerformed(evt);
			}
		});

		f_tipeKoleksi.setEnabled(false);
		f_tipeKoleksi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
		f_tipeKoleksi.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				f_tipeKoleksiFocusLost(evt);
			}
		});
		f_tipeKoleksi.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				f_tipeKoleksiActionPerformed(evt);
			}
		});

		l_tipeKoleksi.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
		l_tipeKoleksi.setForeground(new java.awt.Color(51, 51, 51));
		l_tipeKoleksi.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		l_tipeKoleksi.setText("Tipe Koleksi");
		l_tipeKoleksi.setToolTipText("");
		l_tipeKoleksi.setMaximumSize(new java.awt.Dimension(150, 25));
		l_tipeKoleksi.setMinimumSize(new java.awt.Dimension(150, 25));

		b_tambahKoleksi.setBackground(new java.awt.Color(51, 204, 0));
		b_tambahKoleksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		b_tambahKoleksi.setForeground(new java.awt.Color(255, 255, 255));
		b_tambahKoleksi.setText("Tambah");
		b_tambahKoleksi.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				b_tambahKoleksiActionPerformed(evt);
			}
		});

		b_hapusKoleksi.setBackground(new java.awt.Color(255, 102, 102));
		b_hapusKoleksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		b_hapusKoleksi.setForeground(new java.awt.Color(255, 255, 255));
		b_hapusKoleksi.setText("Hapus");
		b_hapusKoleksi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		b_hapusKoleksi.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				b_hapusKoleksiActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout panel_KoleksiLayout = new javax.swing.GroupLayout(panel_Koleksi);
		panel_Koleksi.setLayout(panel_KoleksiLayout);
		panel_KoleksiLayout.setHorizontalGroup(
			panel_KoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(panel_KoleksiLayout.createSequentialGroup()
					.addContainerGap()
					.addGroup(panel_KoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(panel_KoleksiLayout.createSequentialGroup()
							.addComponent(l_pencarianKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addContainerGap(236, Short.MAX_VALUE))
						.addGroup(panel_KoleksiLayout.createSequentialGroup()
							.addComponent(i_kodeKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
							.addComponent(i_judulKoleksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
							.addComponent(b_cekKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addContainerGap())
						.addGroup(panel_KoleksiLayout.createSequentialGroup()
							.addGroup(panel_KoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(panel_KoleksiLayout.createSequentialGroup()
									.addComponent(l_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
									.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
									.addComponent(f_judulKoleksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGroup(panel_KoleksiLayout.createSequentialGroup()
									.addComponent(l_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
									.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
									.addComponent(f_penerbit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGroup(panel_KoleksiLayout.createSequentialGroup()
									.addComponent(l_isbnIssn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
									.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
									.addComponent(f_isbnIssn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGroup(panel_KoleksiLayout.createSequentialGroup()
									.addComponent(l_tipeKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
									.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
									.addComponent(f_tipeKoleksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
							.addGap(86, 86, 86))))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_KoleksiLayout.createSequentialGroup()
					.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addComponent(b_hapusKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addGap(18, 18, 18)
					.addComponent(b_tambahKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addContainerGap())
		);
		panel_KoleksiLayout.setVerticalGroup(
			panel_KoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(panel_KoleksiLayout.createSequentialGroup()
					.addContainerGap()
					.addComponent(l_pencarianKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addGroup(panel_KoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(b_cekKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(panel_KoleksiLayout.createSequentialGroup()
							.addGroup(panel_KoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(i_judulKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(i_kodeKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
							.addGroup(panel_KoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(l_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(f_judulKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
							.addGroup(panel_KoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(l_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(f_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
							.addGroup(panel_KoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(l_isbnIssn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(f_isbnIssn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
							.addGroup(panel_KoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(l_tipeKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(f_tipeKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addGroup(panel_KoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(b_tambahKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(b_hapusKoleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
					.addContainerGap())
		);

		panel_PeminjamDeadline.setBackground(new java.awt.Color(153, 204, 255));
		panel_PeminjamDeadline.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		panel_PeminjamDeadline.setPreferredSize(new java.awt.Dimension(480, 270));

		l_pencarianPeminjam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		l_pencarianPeminjam.setForeground(new java.awt.Color(0, 0, 0));
		l_pencarianPeminjam.setText("Pencarian Peminjam");

		b_cekPeminjam.setText("Cari");
		b_cekPeminjam.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				b_cekPeminjamActionPerformed(evt);
			}
		});

		i_namaPeminjam.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
		i_namaPeminjam.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				i_namaPeminjamFocusLost(evt);
			}
		});
		i_namaPeminjam.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				i_namaPeminjamActionPerformed(evt);
			}
		});

		i_kodePeminjam.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
		i_kodePeminjam.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				i_kodePeminjamFocusLost(evt);
			}
		});
		i_kodePeminjam.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				i_kodePeminjamActionPerformed(evt);
			}
		});

		l_namaPeminjam.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
		l_namaPeminjam.setForeground(new java.awt.Color(51, 51, 51));
		l_namaPeminjam.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		l_namaPeminjam.setText("Nama");
		l_namaPeminjam.setToolTipText("");
		l_namaPeminjam.setMaximumSize(new java.awt.Dimension(150, 25));
		l_namaPeminjam.setMinimumSize(new java.awt.Dimension(150, 25));

		f_namaPeminjam.setEnabled(false);
		f_namaPeminjam.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
		f_namaPeminjam.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				f_namaPeminjamFocusLost(evt);
			}
		});
		f_namaPeminjam.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				f_namaPeminjamActionPerformed(evt);
			}
		});

		f_maksPinjam.setEnabled(false);
		f_maksPinjam.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
		f_maksPinjam.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				f_maksPinjamFocusLost(evt);
			}
		});
		f_maksPinjam.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				f_maksPinjamActionPerformed(evt);
			}
		});

		l_lamaPinjam.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
		l_lamaPinjam.setForeground(new java.awt.Color(51, 51, 51));
		l_lamaPinjam.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		l_lamaPinjam.setText("Lama Pinjam");
		l_lamaPinjam.setToolTipText("");
		l_lamaPinjam.setMaximumSize(new java.awt.Dimension(150, 25));
		l_lamaPinjam.setMinimumSize(new java.awt.Dimension(150, 25));

		i_lamaPinjam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1 Minggu", "2 Minggu", "3 Minggu", "4 Minggu"}));

		l_dari.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
		l_dari.setForeground(new java.awt.Color(51, 51, 51));
		l_dari.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		l_dari.setText("Dari");
		l_dari.setToolTipText("");
		l_dari.setMaximumSize(new java.awt.Dimension(150, 25));
		l_dari.setMinimumSize(new java.awt.Dimension(150, 25));

		f_dari.setEnabled(false);
		f_dari.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
		f_dari.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				f_dariFocusLost(evt);
			}
		});
		f_dari.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				f_dariActionPerformed(evt);
			}
		});

		b_kosongkanTransaksi.setBackground(new java.awt.Color(255, 102, 102));
		b_kosongkanTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		b_kosongkanTransaksi.setForeground(new java.awt.Color(255, 255, 255));
		b_kosongkanTransaksi.setText("Kosongkan");
		b_kosongkanTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		b_kosongkanTransaksi.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				b_kosongkanTransaksiActionPerformed(evt);
			}
		});

		b_konfirmasiTransaksi.setBackground(new java.awt.Color(51, 204, 0));
		b_konfirmasiTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		b_konfirmasiTransaksi.setForeground(new java.awt.Color(255, 255, 255));
		b_konfirmasiTransaksi.setText("Simpan");
		b_konfirmasiTransaksi.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				b_konfirmasiTransaksiActionPerformed(evt);
			}
		});

		b_kembali.setBackground(new java.awt.Color(255, 204, 153));
		b_kembali.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		b_kembali.setForeground(new java.awt.Color(255, 255, 255));
		b_kembali.setText("Kembali");
		b_kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		b_kembali.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				b_kembaliActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout panel_PeminjamDeadlineLayout = new javax.swing.GroupLayout(panel_PeminjamDeadline);
		panel_PeminjamDeadline.setLayout(panel_PeminjamDeadlineLayout);
		panel_PeminjamDeadlineLayout.setHorizontalGroup(
			panel_PeminjamDeadlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(panel_PeminjamDeadlineLayout.createSequentialGroup()
					.addContainerGap()
					.addGroup(panel_PeminjamDeadlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_PeminjamDeadlineLayout.createSequentialGroup()
							.addGroup(panel_PeminjamDeadlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(panel_PeminjamDeadlineLayout.createSequentialGroup()
									.addComponent(i_kodePeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
									.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
									.addComponent(i_namaPeminjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGroup(panel_PeminjamDeadlineLayout.createSequentialGroup()
									.addComponent(l_namaPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
									.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
									.addComponent(f_namaPeminjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_PeminjamDeadlineLayout.createSequentialGroup()
									.addComponent(l_lamaPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
									.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
									.addComponent(i_lamaPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
									.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
									.addComponent(l_dari, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
									.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
									.addComponent(f_dari, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
							.addGroup(panel_PeminjamDeadlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(panel_PeminjamDeadlineLayout.createSequentialGroup()
									.addComponent(f_maksPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
									.addGap(40, 40, 40))
								.addComponent(b_cekPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
						.addGroup(panel_PeminjamDeadlineLayout.createSequentialGroup()
							.addComponent(l_pencarianPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addGap(0, 0, Short.MAX_VALUE))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_PeminjamDeadlineLayout.createSequentialGroup()
							.addComponent(b_kembali)
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(b_kosongkanTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addGap(18, 18, 18)
							.addComponent(b_konfirmasiTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
					.addContainerGap())
		);
		panel_PeminjamDeadlineLayout.setVerticalGroup(
			panel_PeminjamDeadlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(panel_PeminjamDeadlineLayout.createSequentialGroup()
					.addContainerGap()
					.addComponent(l_pencarianPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addGroup(panel_PeminjamDeadlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(panel_PeminjamDeadlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
							.addComponent(i_namaPeminjam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addComponent(i_kodePeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addComponent(b_cekPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addGroup(panel_PeminjamDeadlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(f_maksPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(f_namaPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(l_namaPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addGroup(panel_PeminjamDeadlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(f_dari, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(panel_PeminjamDeadlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
							.addComponent(l_lamaPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addComponent(i_lamaPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addComponent(l_dari, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
					.addGroup(panel_PeminjamDeadlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(b_konfirmasiTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(b_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(b_kosongkanTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
					.addGap(10, 10, 10))
		);

		panel_keranjangTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		panel_keranjangTable.setPreferredSize(new java.awt.Dimension(480, 270));

		tabelKeranjang.setModel(new javax.swing.table.DefaultTableModel(
			new Object[][]{

			},
			new String[]{
				"id", "title", "tipe", "tersedia"
			}
		) {
			Class[] types = new Class[]{
				java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
			};
			boolean[] canEdit = new boolean[]{
				false, false, false, false
			};

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		tabelKeranjang.getTableHeader().setReorderingAllowed(false);
		scrollPane_tabelKeranjang.setViewportView(tabelKeranjang);

		l_tabelKeranjang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		l_tabelKeranjang.setText("Tabel Keranjang");

		javax.swing.GroupLayout panel_keranjangTableLayout = new javax.swing.GroupLayout(panel_keranjangTable);
		panel_keranjangTable.setLayout(panel_keranjangTableLayout);
		panel_keranjangTableLayout.setHorizontalGroup(
			panel_keranjangTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(panel_keranjangTableLayout.createSequentialGroup()
					.addContainerGap()
					.addGroup(panel_keranjangTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(scrollPane_tabelKeranjang)
						.addComponent(l_tabelKeranjang, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
					.addContainerGap())
		);
		panel_keranjangTableLayout.setVerticalGroup(
			panel_keranjangTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_keranjangTableLayout.createSequentialGroup()
					.addContainerGap()
					.addComponent(l_tabelKeranjang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addComponent(scrollPane_tabelKeranjang, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addContainerGap())
		);

		panel_transaksiTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
		panel_transaksiTable.setPreferredSize(new java.awt.Dimension(480, 270));

		tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
			new Object[][]{

			},
			new String[]{
				"id", "customer id", "at", "end", "amount"
			}
		) {
			Class[] types = new Class[]{
				java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
			};
			boolean[] canEdit = new boolean[]{
				false, false, false, false, false
			};

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		tabelTransaksi.getTableHeader().setReorderingAllowed(false);
		scrollPane_tabelTransaksi.setViewportView(tabelTransaksi);

		l_tabelTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		l_tabelTransaksi.setText("Tabel Transaksi");

		javax.swing.GroupLayout panel_transaksiTableLayout = new javax.swing.GroupLayout(panel_transaksiTable);
		panel_transaksiTable.setLayout(panel_transaksiTableLayout);
		panel_transaksiTableLayout.setHorizontalGroup(
			panel_transaksiTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(panel_transaksiTableLayout.createSequentialGroup()
					.addContainerGap()
					.addGroup(panel_transaksiTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(scrollPane_tabelTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
						.addComponent(l_tabelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
					.addContainerGap())
		);
		panel_transaksiTableLayout.setVerticalGroup(
			panel_transaksiTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_transaksiTableLayout.createSequentialGroup()
					.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addComponent(l_tabelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(scrollPane_tabelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addContainerGap())
		);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(panel_Koleksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(panel_PeminjamDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addComponent(panel_transaksiTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(panel_keranjangTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addGroup(layout.createSequentialGroup()
							.addComponent(panel_Koleksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addGap(0, 0, 0)
							.addComponent(panel_PeminjamDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup()
							.addComponent(panel_keranjangTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addGap(0, 0, 0)
							.addComponent(panel_transaksiTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
					.addGap(0, 0, 0))
		);

		setSize(new java.awt.Dimension(974, 577));
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * Mengatur warna background pada sebuah komponen menjadi merah
	 */
	private void setRedBG(Component... components) {
		for (Component c : components) {
			c.setBackground(I_RED);
		}
	}

	/**
	 * Mengatur warna background pada sebuah komponen menjadi putih
	 */
	private void setWhiteBG(Component... components) {
		for (Component c : components) {
			c.setBackground(new Color(0xFFFFFF));
		}
	}

	/**
	 * Mengisi field informasi koleksi
	 */
	private void fillFieldKoleksi(Koleksi koleksi) {
		f_judulKoleksi.setText(koleksi.getJudul());
		f_penerbit.setText(koleksi.getPenerbit());
		if (koleksi instanceof Buku b) {
			f_isbnIssn.setText(b.getIsbn());
		} else if (koleksi instanceof Majalah m) {
			f_isbnIssn.setText(m.getIssn());
		} else if (koleksi instanceof Disk d) {
			f_isbnIssn.setText(d.getIsbn());
		}
		f_tipeKoleksi.setText(koleksi.getTipe());
	}

	/**
	 * Mengosongkan field informasi koleksi dan current koleksi
	 */
	private void kosongkanFieldKoleksi() {
		i_kodeKoleksi.setText("");
		i_judulKoleksi.setText("");
		f_judulKoleksi.setText("");
		f_penerbit.setText("");
		f_isbnIssn.setText("");
		f_tipeKoleksi.setText("");
		currentKoleksi = null;

		setWhiteBG(i_kodeKoleksi, i_judulKoleksi);
	}

	/**
	 * Mengosongkan field informasi peminjam dan current peminjam
	 */
	private void kosongkanFieldPeminjam() {
		i_kodePeminjam.setText("");
		i_namaPeminjam.setText("");
		f_namaPeminjam.setText("");
		f_maksPinjam.setText("");
		f_dari.setText("");
		currentPeminjam = null;

		setWhiteBG(i_kodePeminjam, i_namaPeminjam);
	}

	/**
	 * Tombol untuk mengecek koleksi dengan data yang dimasukkan dari database
	 */
	private void b_cekKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cekKoleksiActionPerformed
		// TODO add your handling code here:
		final var kodeKoleksi = i_kodeKoleksi.getText().trim();
		final var judulKoleksi = i_judulKoleksi.getText().trim();

		/* Cek apakah kedua kolom kosong */
		if (kodeKoleksi.equals("") && judulKoleksi.equals("")) {
			setRedBG(i_kodeKoleksi, i_judulKoleksi);
			return;
		}

		/* Cari dengan kode koleksi */
		if (!kodeKoleksi.equals("")) {
			final Koleksi koleksi = DatabaseHandler.findKoleksi(kodeKoleksi);
			System.out.println(koleksi);

			setRedBG(i_kodeKoleksi);
			if (koleksi != null) { // Guard
				setWhiteBG(i_kodeKoleksi);
				currentKoleksi = koleksi;
				fillFieldKoleksi(currentKoleksi);
				// Jika hasil dengan kode tidak null maka tidak usah mengecek judul koleksi
				return;
			}
		}

		/* Cari dengan judul koleksi */
		if (!judulKoleksi.equals("")) {
			final Koleksi koleksi = DatabaseHandler.findKoleksiByTitle(judulKoleksi);
			System.out.println(koleksi);

			setRedBG(i_judulKoleksi);
			if (koleksi != null) { // Guard
				setWhiteBG(i_judulKoleksi);
				currentKoleksi = koleksi;
				fillFieldKoleksi(currentKoleksi);
			}
		}
	}//GEN-LAST:event_b_cekKoleksiActionPerformed

	private void i_judulKoleksiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_i_judulKoleksiFocusLost
		// TODO add your handling code here:
	}//GEN-LAST:event_i_judulKoleksiFocusLost

	private void i_judulKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_judulKoleksiActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_i_judulKoleksiActionPerformed

	private void i_kodeKoleksiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_i_kodeKoleksiFocusLost
		// TODO add your handling code here:
	}//GEN-LAST:event_i_kodeKoleksiFocusLost

	private void i_kodeKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_kodeKoleksiActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_i_kodeKoleksiActionPerformed

	private void b_cekPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cekPeminjamActionPerformed
		final var kodePeminjam = i_kodePeminjam.getText().trim();
		final var namaPeminjam = i_namaPeminjam.getText().trim();

		/* Cek apakah kedua kolom kosong */
		if (kodePeminjam.equals("") && namaPeminjam.equals("")) {
			setRedBG(i_kodePeminjam, i_namaPeminjam);
			return;
		}

		/* Cari dengan kode peminjam */
		if (!kodePeminjam.equals("")) {
			final Peminjam peminjam = DatabaseHandler.findPeminjam(kodePeminjam);

			setRedBG(i_kodePeminjam);
			if (peminjam != null) { // Guard
				setWhiteBG(i_kodePeminjam);
				currentPeminjam = peminjam;
				f_namaPeminjam.setText(currentPeminjam.getNama());
				f_maksPinjam.setText(String.valueOf(currentPeminjam.getMaksPinjam()));
				f_dari.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")));
				return;
			}
		}

		/* Cari dengan nama peminjam */
		if (!namaPeminjam.equals("")) {
			final Peminjam peminjam = DatabaseHandler.findPeminjamByName(namaPeminjam);

			setRedBG(i_namaPeminjam);
			if (peminjam != null) { // Guard
				setWhiteBG(i_namaPeminjam);
				currentPeminjam = peminjam;
				f_namaPeminjam.setText(currentPeminjam.getNama());
				f_maksPinjam.setText(String.valueOf(currentPeminjam.getMaksPinjam()));
				f_dari.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")));
			}
		}
	}//GEN-LAST:event_b_cekPeminjamActionPerformed

	private void i_namaPeminjamFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_i_namaPeminjamFocusLost
		// TODO add your handling code here:
	}//GEN-LAST:event_i_namaPeminjamFocusLost

	private void i_namaPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_namaPeminjamActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_i_namaPeminjamActionPerformed

	private void i_kodePeminjamFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_i_kodePeminjamFocusLost
		// TODO add your handling code here:
	}//GEN-LAST:event_i_kodePeminjamFocusLost

	private void i_kodePeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_kodePeminjamActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_i_kodePeminjamActionPerformed

	private void f_judulKoleksiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f_judulKoleksiFocusLost
		// TODO add your handling code here:
	}//GEN-LAST:event_f_judulKoleksiFocusLost

	private void f_judulKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_judulKoleksiActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_f_judulKoleksiActionPerformed

	private void f_penerbitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f_penerbitFocusLost
		// TODO add your handling code here:
	}//GEN-LAST:event_f_penerbitFocusLost

	private void f_penerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_penerbitActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_f_penerbitActionPerformed

	private void f_isbnIssnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f_isbnIssnFocusLost
		// TODO add your handling code here:
	}//GEN-LAST:event_f_isbnIssnFocusLost

	private void f_isbnIssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_isbnIssnActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_f_isbnIssnActionPerformed

	private void f_tipeKoleksiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f_tipeKoleksiFocusLost
		// TODO add your handling code here:
	}//GEN-LAST:event_f_tipeKoleksiFocusLost

	private void f_tipeKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_tipeKoleksiActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_f_tipeKoleksiActionPerformed

	private void f_namaPeminjamFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f_namaPeminjamFocusLost
		// TODO add your handling code here:
	}//GEN-LAST:event_f_namaPeminjamFocusLost

	private void f_namaPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_namaPeminjamActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_f_namaPeminjamActionPerformed

	private void f_maksPinjamFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f_maksPinjamFocusLost
		// TODO add your handling code here:
	}//GEN-LAST:event_f_maksPinjamFocusLost

	private void f_maksPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_maksPinjamActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_f_maksPinjamActionPerformed

	private void f_dariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f_dariFocusLost
		// TODO add your handling code here:
	}//GEN-LAST:event_f_dariFocusLost

	private void f_dariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_dariActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_f_dariActionPerformed

	private void b_kosongkanTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_kosongkanTransaksiActionPerformed
		kosongkanFieldKoleksi();
		kosongkanFieldPeminjam();
	}//GEN-LAST:event_b_kosongkanTransaksiActionPerformed

	private void b_konfirmasiTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_konfirmasiTransaksiActionPerformed
		/* Variabel-variabel penyimpan data DENGAN regex */

	}//GEN-LAST:event_b_konfirmasiTransaksiActionPerformed

	private void b_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_kembaliActionPerformed
		setVisible(false);
	}//GEN-LAST:event_b_kembaliActionPerformed

	private void b_tambahKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tambahKoleksiActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_b_tambahKoleksiActionPerformed

	private void b_hapusKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_hapusKoleksiActionPerformed
		kosongkanFieldKoleksi();
	}//GEN-LAST:event_b_hapusKoleksiActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton b_cekKoleksi;
	private javax.swing.JButton b_cekPeminjam;
	private javax.swing.JButton b_hapusKoleksi;
	private javax.swing.JButton b_kembali;
	private javax.swing.JButton b_konfirmasiTransaksi;
	private javax.swing.JButton b_kosongkanTransaksi;
	private javax.swing.JButton b_tambahKoleksi;
	private java.awt.TextField f_dari;
	private java.awt.TextField f_isbnIssn;
	private java.awt.TextField f_judulKoleksi;
	private java.awt.TextField f_maksPinjam;
	private java.awt.TextField f_namaPeminjam;
	private java.awt.TextField f_penerbit;
	private java.awt.TextField f_tipeKoleksi;
	private java.awt.TextField i_judulKoleksi;
	private java.awt.TextField i_kodeKoleksi;
	private java.awt.TextField i_kodePeminjam;
	private javax.swing.JComboBox<String> i_lamaPinjam;
	private java.awt.TextField i_namaPeminjam;
	private javax.swing.JLabel l_dari;
	private javax.swing.JLabel l_isbnIssn;
	private javax.swing.JLabel l_lamaPinjam;
	private javax.swing.JLabel l_nama;
	private javax.swing.JLabel l_namaPeminjam;
	private javax.swing.JLabel l_pencarianKoleksi;
	private javax.swing.JLabel l_pencarianPeminjam;
	private javax.swing.JLabel l_penerbit;
	private javax.swing.JLabel l_tabelKeranjang;
	private javax.swing.JLabel l_tabelTransaksi;
	private javax.swing.JLabel l_tipeKoleksi;
	private javax.swing.JPanel panel_Koleksi;
	private javax.swing.JPanel panel_PeminjamDeadline;
	private javax.swing.JPanel panel_keranjangTable;
	private javax.swing.JPanel panel_transaksiTable;
	private javax.swing.JScrollPane scrollPane_tabelKeranjang;
	private javax.swing.JScrollPane scrollPane_tabelTransaksi;
	private javax.swing.JTable tabelKeranjang;
	private javax.swing.JTable tabelTransaksi;
	// End of variables declaration//GEN-END:variables
}
